export type AiCopy = {
  assistant: string;
  online: string;
  subtitle: string;
  start: string;
  askAnything: string;
  newChat: string;
  language: string;
  readAloudOn: string;
  readAloudOff: string;
  suggested: string;
  cropAdvice: string;
  irrigation: string;
  pest: string;
  weather: string;
  market: string;
  previousChats: string;
  noChats: string;
  farmAware: string;
  processing: string;
  listening: string;
  temporarilyUnavailable: string;
  unavailableDesc: string;
  tryAgain: string;
  farmDataSafe: string;
  profileTip: string;
  askPlaceholder: string;
};

const EN: AiCopy = {
  assistant: 'Uzhavan AI', online: 'Online · AI Farming Assistant',
  subtitle: 'Ask questions about your crops, soil, weather, pests, irrigation, market prices and farm activities.',
  start: 'Start a conversation', askAnything: 'Ask me anything about your farm', newChat: 'New Chat', language: 'Language',
  readAloudOn: 'Read Aloud: On', readAloudOff: 'Read Aloud: Off', suggested: 'Suggested Questions', cropAdvice: 'Crop advice',
  irrigation: 'Irrigation', pest: 'Pest & disease', weather: 'Weather', market: 'Market', previousChats: 'Previous Chats',
  noChats: 'No saved conversations yet.', farmAware: 'Farm-aware AI', processing: 'Processing', listening: 'Listening',
  temporarilyUnavailable: 'Uzhavan AI is temporarily unavailable',
  unavailableDesc: 'We could not generate an answer right now. Your farm data is safe. Please try again in a few moments.',
  tryAgain: 'Try Again', farmDataSafe: 'Your farm data is safe.', profileTip: 'Complete your Farm Memory profile for personalised advice.',
  askPlaceholder: 'Ask Uzhavan AI anything…',
};

const copies: Record<string, AiCopy> = {
  en: EN,
  ta: {...EN, assistant:'உழவன் AI', online:'ஆன்லைன் · AI விவசாய உதவியாளர்', subtitle:'உங்கள் பயிர்கள், மண், வானிலை, பூச்சிகள், நீர்ப்பாசனம், சந்தை விலைகள் மற்றும் பண்ணை செயல்பாடுகள் குறித்து கேளுங்கள்.', start:'உரையாடலைத் தொடங்குங்கள்', askAnything:'உங்கள் பண்ணையைப் பற்றி எதையும் கேளுங்கள்', newChat:'புதிய உரையாடல்', language:'மொழி', readAloudOn:'சத்தமாக வாசிப்பு: இயக்கத்தில்', readAloudOff:'சத்தமாக வாசிப்பு: முடக்கப்பட்டுள்ளது', suggested:'பரிந்துரைக்கப்பட்ட கேள்விகள்', cropAdvice:'பயிர் ஆலோசனை', irrigation:'நீர்ப்பாசனம்', pest:'பூச்சி மற்றும் நோய்', weather:'வானிலை', market:'சந்தை', previousChats:'முந்தைய உரையாடல்கள்', noChats:'சேமிக்கப்பட்ட உரையாடல்கள் இல்லை.', farmAware:'பண்ணை சார்ந்த AI', processing:'செயலாக்கப்படுகிறது', listening:'கேட்கிறது', temporarilyUnavailable:'உழவன் AI தற்காலிகமாக கிடைக்கவில்லை', unavailableDesc:'இப்போது பதிலை உருவாக்க முடியவில்லை. உங்கள் பண்ணைத் தரவு பாதுகாப்பாக உள்ளது. சில நிமிடங்களில் மீண்டும் முயற்சிக்கவும்.', tryAgain:'மீண்டும் முயற்சி', farmDataSafe:'உங்கள் பண்ணைத் தரவு பாதுகாப்பாக உள்ளது.', profileTip:'தனிப்பயனாக்கப்பட்ட ஆலோசனைக்கு உங்கள் பண்ணை நினைவக சுயவிவரத்தை முடிக்கவும்.', askPlaceholder:'உழவன் AI-யிடம் எதையும் கேளுங்கள்…'},
  hi: {...EN, assistant:'उझवन AI', online:'ऑनलाइन · AI कृषि सहायक', subtitle:'अपनी फसल, मिट्टी, मौसम, कीट, सिंचाई, बाजार भाव और खेती की गतिविधियों के बारे में पूछें।', start:'बातचीत शुरू करें', askAnything:'अपने खेत के बारे में कुछ भी पूछें', newChat:'नई बातचीत', language:'भाषा', readAloudOn:'जोर से पढ़ें: चालू', readAloudOff:'जोर से पढ़ें: बंद', suggested:'सुझाए गए प्रश्न', cropAdvice:'फसल सलाह', irrigation:'सिंचाई', pest:'कीट और रोग', weather:'मौसम', market:'बाज़ार', previousChats:'पिछली बातचीत', noChats:'अभी कोई बातचीत सहेजी नहीं गई है।', farmAware:'खेत-आधारित AI', processing:'प्रक्रिया जारी है', listening:'सुन रहा है', temporarilyUnavailable:'उझवन AI अस्थायी रूप से उपलब्ध नहीं है', unavailableDesc:'अभी उत्तर तैयार नहीं किया जा सका। आपका खेत डेटा सुरक्षित है। कुछ देर बाद फिर प्रयास करें।', tryAgain:'फिर प्रयास करें', farmDataSafe:'आपका खेत डेटा सुरक्षित है।', profileTip:'व्यक्तिगत सलाह के लिए अपना किसान प्रोफ़ाइल पूरा करें।', askPlaceholder:'उझवन AI से कुछ भी पूछें…'},
  te: {...EN, assistant:'ఉజవన్ AI', online:'ఆన్‌లైన్ · AI వ్యవసాయ సహాయకుడు', subtitle:'మీ పంటలు, నేల, వాతావరణం, పురుగులు, నీటిపారుదల, మార్కెట్ ధరలు మరియు వ్యవసాయ కార్యకలాపాల గురించి అడగండి.', start:'సంభాషణ ప్రారంభించండి', askAnything:'మీ పొలం గురించి ఏదైనా అడగండి', newChat:'కొత్త చాట్', language:'భాష', readAloudOn:'గట్టిగా చదవడం: ఆన్', readAloudOff:'గట్టిగా చదవడం: ఆఫ్', suggested:'సూచించిన ప్రశ్నలు', cropAdvice:'పంట సలహా', irrigation:'నీటిపారుదల', pest:'పురుగులు మరియు వ్యాధులు', weather:'వాతావరణం', market:'మార్కెట్', previousChats:'మునుపటి చాట్‌లు', noChats:'ఇంకా సేవ్ చేసిన సంభాషణలు లేవు.', farmAware:'పొలం ఆధారిత AI', processing:'ప్రాసెస్ చేస్తోంది', listening:'వింటోంది', temporarilyUnavailable:'ఉజవన్ AI తాత్కాలికంగా అందుబాటులో లేదు', unavailableDesc:'ఇప్పుడు సమాధానం రూపొందించలేకపోయాం. మీ పొలం డేటా సురక్షితంగా ఉంది. కొద్దిసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.', tryAgain:'మళ్లీ ప్రయత్నించండి', farmDataSafe:'మీ పొలం డేటా సురక్షితంగా ఉంది.', profileTip:'వ్యక్తిగత సలహా కోసం మీ రైతు ప్రొఫైల్‌ను పూర్తి చేయండి.', askPlaceholder:'ఉజవన్ AIని ఏదైనా అడగండి…'},
  ml: {...EN, assistant:'ഉഴവൻ AI', online:'ഓൺലൈൻ · AI കൃഷി സഹായി', subtitle:'വിളകൾ, മണ്ണ്, കാലാവസ്ഥ, കീടങ്ങൾ, ജലസേചനം, വിപണി വിലകൾ, കൃഷി പ്രവർത്തനങ്ങൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കൂ.', start:'സംഭാഷണം ആരംഭിക്കുക', askAnything:'നിങ്ങളുടെ കൃഷിയിടത്തെക്കുറിച്ച് എന്തും ചോദിക്കൂ', newChat:'പുതിയ ചാറ്റ്', language:'ഭാഷ', readAloudOn:'വായിച്ച് കേൾപ്പിക്കുക: ഓൺ', readAloudOff:'വായിച്ച് കേൾപ്പിക്കുക: ഓഫ്', suggested:'നിർദ്ദേശിച്ച ചോദ്യങ്ങൾ', cropAdvice:'വിള ഉപദേശം', irrigation:'ജലസേചനം', pest:'കീടങ്ങളും രോഗങ്ങളും', weather:'കാലാവസ്ഥ', market:'വിപണി', previousChats:'മുൻ ചാറ്റുകൾ', noChats:'സംരക്ഷിച്ച സംഭാഷണങ്ങൾ ഒന്നുമില്ല.', farmAware:'കൃഷിയിടം അടിസ്ഥാനമാക്കിയ AI', processing:'പ്രോസസ്സ് ചെയ്യുന്നു', listening:'കേൾക്കുന്നു', temporarilyUnavailable:'ഉഴവൻ AI താൽക്കാലികമായി ലഭ്യമല്ല', unavailableDesc:'ഇപ്പോൾ മറുപടി സൃഷ്ടിക്കാനായില്ല. നിങ്ങളുടെ കൃഷിയിട ഡാറ്റ സുരക്ഷിതമാണ്. കുറച്ച് കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക.', tryAgain:'വീണ്ടും ശ്രമിക്കുക', farmDataSafe:'നിങ്ങളുടെ കൃഷിയിട ഡാറ്റ സുരക്ഷിതമാണ്.', profileTip:'വ്യക്തിഗത ഉപദേശത്തിനായി നിങ്ങളുടെ കർഷക പ്രൊഫൈൽ പൂർത്തിയാക്കുക.', askPlaceholder:'ഉഴവൻ AI-യോട് എന്തും ചോദിക്കൂ…'},
  kn: {...EN, assistant:'ಉಳುವನ್ AI', online:'ಆನ್‌ಲೈನ್ · AI ಕೃಷಿ ಸಹಾಯಕ', subtitle:'ನಿಮ್ಮ ಬೆಳೆಗಳು, ಮಣ್ಣು, ಹವಾಮಾನ, ಕೀಟಗಳು, ನೀರಾವರಿ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು ಮತ್ತು ಕೃಷಿ ಚಟುವಟಿಕೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ.', start:'ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಿ', askAnything:'ನಿಮ್ಮ ಹೊಲದ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ', newChat:'ಹೊಸ ಚಾಟ್', language:'ಭಾಷೆ', readAloudOn:'ಓದಿ ಕೇಳಿಸಿ: ಆನ್', readAloudOff:'ಓದಿ ಕೇಳಿಸಿ: ಆಫ್', suggested:'ಸೂಚಿಸಿದ ಪ್ರಶ್ನೆಗಳು', cropAdvice:'ಬೆಳೆ ಸಲಹೆ', irrigation:'ನೀರಾವರಿ', pest:'ಕೀಟ ಮತ್ತು ರೋಗ', weather:'ಹವಾಮಾನ', market:'ಮಾರುಕಟ್ಟೆ', previousChats:'ಹಿಂದಿನ ಚಾಟ್‌ಗಳು', noChats:'ಯಾವುದೇ ಸಂಭಾಷಣೆಗಳು ಉಳಿಸಲಾಗಿಲ್ಲ.', farmAware:'ಹೊಲ ಆಧಾರಿತ AI', processing:'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ', listening:'ಕೇಳುತ್ತಿದೆ', temporarilyUnavailable:'ಉಳುವನ್ AI ತಾತ್ಕಾಲಿಕವಾಗಿ ಲಭ್ಯವಿಲ್ಲ', unavailableDesc:'ಈಗ ಉತ್ತರವನ್ನು ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ನಿಮ್ಮ ಹೊಲದ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', tryAgain:'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ', farmDataSafe:'ನಿಮ್ಮ ಹೊಲದ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ.', profileTip:'ವೈಯಕ್ತಿಕ ಸಲಹೆಗಾಗಿ ನಿಮ್ಮ ರೈತ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ.', askPlaceholder:'ಉಳುವನ್ AIಗೆ ಏನಾದರೂ ಕೇಳಿ…'},
  bn: {...EN, assistant:'উঝাভান AI', online:'অনলাইন · AI কৃষি সহায়ক', subtitle:'আপনার ফসল, মাটি, আবহাওয়া, পোকা, সেচ, বাজারদর ও কৃষিকাজ সম্পর্কে প্রশ্ন করুন.', start:'কথোপকথন শুরু করুন', askAnything:'আপনার খামার সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন', newChat:'নতুন চ্যাট', language:'ভাষা', readAloudOn:'জোরে পড়া: চালু', readAloudOff:'জোরে পড়া: বন্ধ', suggested:'প্রস্তাবিত প্রশ্ন', cropAdvice:'ফসল পরামর্শ', irrigation:'সেচ', pest:'পোকা ও রোগ', weather:'আবহাওয়া', market:'বাজার', previousChats:'আগের চ্যাট', noChats:'কোনো সংরক্ষিত কথোপকথন নেই।', farmAware:'খামার-ভিত্তিক AI', processing:'প্রক্রিয়াকরণ চলছে', listening:'শুনছে', temporarilyUnavailable:'উঝাভান AI সাময়িকভাবে অনুপলব্ধ', unavailableDesc:'এখন উত্তর তৈরি করা যায়নি। আপনার খামারের ডেটা নিরাপদ। কিছুক্ষণ পরে আবার চেষ্টা করুন।', tryAgain:'আবার চেষ্টা করুন', farmDataSafe:'আপনার খামারের ডেটা নিরাপদ।', profileTip:'ব্যক্তিগত পরামর্শের জন্য আপনার কৃষক প্রোফাইল সম্পূর্ণ করুন।', askPlaceholder:'উঝাভান AI-কে যেকোনো কিছু জিজ্ঞাসা করুন…'},
  mr: {...EN, assistant:'उझवन AI', online:'ऑनलाइन · AI कृषी सहाय्यक', subtitle:'तुमच्या पिके, माती, हवामान, किडी, सिंचन, बाजारभाव आणि शेतीच्या कामांबद्दल विचारा.', start:'संभाषण सुरू करा', askAnything:'तुमच्या शेताबद्दल काहीही विचारा', newChat:'नवीन चॅट', language:'भाषा', readAloudOn:'मोठ्याने वाचा: सुरू', readAloudOff:'मोठ्याने वाचा: बंद', suggested:'सुचवलेले प्रश्न', cropAdvice:'पीक सल्ला', irrigation:'सिंचन', pest:'किडी व रोग', weather:'हवामान', market:'बाजार', previousChats:'मागील चॅट', noChats:'अद्याप जतन केलेले संभाषण नाही.', farmAware:'शेत-आधारित AI', processing:'प्रक्रिया सुरू आहे', listening:'ऐकत आहे', temporarilyUnavailable:'उझवन AI तात्पुरते उपलब्ध नाही', unavailableDesc:'आत्ता उत्तर तयार करता आले नाही. तुमच्या शेताचा डेटा सुरक्षित आहे. थोड्या वेळाने पुन्हा प्रयत्न करा.', tryAgain:'पुन्हा प्रयत्न करा', farmDataSafe:'तुमच्या शेताचा डेटा सुरक्षित आहे.', profileTip:'वैयक्तिक सल्ल्यासाठी तुमचे शेतकरी प्रोफाइल पूर्ण करा.', askPlaceholder:'उझवन AI ला काहीही विचारा…'},
  gu: {...EN, assistant:'ઉઝવન AI', online:'ઓનલાઇન · AI કૃષિ સહાયક', subtitle:'તમારા પાક, જમીન, હવામાન, જીવાતો, સિંચાઈ, બજાર ભાવ અને ખેતીની પ્રવૃત્તિઓ વિશે પૂછો.', start:'વાતચીત શરૂ કરો', askAnything:'તમારા ખેતર વિશે કંઈપણ પૂછો', newChat:'નવી ચેટ', language:'ભાષા', readAloudOn:'મોટેથી વાંચો: ચાલુ', readAloudOff:'મોટેથી વાંચો: બંધ', suggested:'સૂચવેલા પ્રશ્નો', cropAdvice:'પાક સલાહ', irrigation:'સિંચાઈ', pest:'જીવાત અને રોગ', weather:'હવામાન', market:'બજાર', previousChats:'પહેલાની ચેટ્સ', noChats:'હજુ સુધી કોઈ સાચવેલી વાતચીત નથી.', farmAware:'ખેતર આધારિત AI', processing:'પ્રક્રિયા ચાલી રહી છે', listening:'સાંભળી રહ્યું છે', temporarilyUnavailable:'ઉઝવન AI અસ્થાયી રીતે ઉપલબ્ધ નથી', unavailableDesc:'હમણાં જવાબ બનાવી શક્યા નથી. તમારો ખેતર ડેટા સુરક્ષિત છે. થોડા સમય પછી ફરી પ્રયાસ કરો.', tryAgain:'ફરી પ્રયાસ કરો', farmDataSafe:'તમારો ખેતર ડેટા સુરક્ષિત છે.', profileTip:'વ્યક્તિગત સલાહ માટે તમારું ખેડૂત પ્રોફાઇલ પૂર્ણ કરો.', askPlaceholder:'ઉઝવન AIને કંઈપણ પૂછો…'},
  pa: {...EN, assistant:'ਉਝਵਨ AI', online:'ਆਨਲਾਈਨ · AI ਖੇਤੀ ਸਹਾਇਕ', subtitle:'ਆਪਣੀਆਂ ਫਸਲਾਂ, ਮਿੱਟੀ, ਮੌਸਮ, ਕੀੜਿਆਂ, ਸਿੰਚਾਈ, ਬਾਜ਼ਾਰ ਭਾਅ ਅਤੇ ਖੇਤੀ ਕੰਮਾਂ ਬਾਰੇ ਪੁੱਛੋ.', start:'ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ', askAnything:'ਆਪਣੇ ਖੇਤ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ', newChat:'ਨਵੀਂ ਚੈਟ', language:'ਭਾਸ਼ਾ', readAloudOn:'ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਪੜ੍ਹੋ: ਚਾਲੂ', readAloudOff:'ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਪੜ੍ਹੋ: ਬੰਦ', suggested:'ਸੁਝਾਏ ਸਵਾਲ', cropAdvice:'ਫਸਲ ਸਲਾਹ', irrigation:'ਸਿੰਚਾਈ', pest:'ਕੀੜੇ ਅਤੇ ਰੋਗ', weather:'ਮੌਸਮ', market:'ਬਾਜ਼ਾਰ', previousChats:'ਪਿਛਲੀਆਂ ਚੈਟਾਂ', noChats:'ਹਾਲੇ ਕੋਈ ਸੁਰੱਖਿਅਤ ਗੱਲਬਾਤ ਨਹੀਂ।', farmAware:'ਖੇਤ-ਅਧਾਰਿਤ AI', processing:'ਪ੍ਰਕਿਰਿਆ ਜਾਰੀ ਹੈ', listening:'ਸੁਣ ਰਿਹਾ ਹੈ', temporarilyUnavailable:'ਉਝਵਨ AI ਅਸਥਾਈ ਤੌਰ ਤੇ ਉਪਲਬਧ ਨਹੀਂ', unavailableDesc:'ਹੁਣ ਜਵਾਬ ਤਿਆਰ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਤੁਹਾਡਾ ਖੇਤ ਡਾਟਾ ਸੁਰੱਖਿਅਤ ਹੈ। ਕੁਝ ਦੇਰ ਬਾਅਦ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।', tryAgain:'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ', farmDataSafe:'ਤੁਹਾਡਾ ਖੇਤ ਡਾਟਾ ਸੁਰੱਖਿਅਤ ਹੈ.', profileTip:'ਨਿੱਜੀ ਸਲਾਹ ਲਈ ਆਪਣਾ ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ ਪੂਰਾ ਕਰੋ.', askPlaceholder:'ਉਝਵਨ AI ਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ…'},
  or: {...EN, assistant:'ଉଝାଭାନ AI', online:'ଅନଲାଇନ୍ · AI କୃଷି ସହାୟକ', subtitle:'ଆପଣଙ୍କ ଫସଲ, ମାଟି, ପାଣିପାଗ, କୀଟ, ଜଳସେଚନ, ବଜାର ଦର ଓ ଚାଷ କାର୍ଯ୍ୟ ବିଷୟରେ ପଚାରନ୍ତୁ।', start:'କଥାବାର୍ତ୍ତା ଆରମ୍ଭ କରନ୍ତୁ', askAnything:'ଆପଣଙ୍କ ଚାଷ ବିଷୟରେ କିଛି ବି ପଚାରନ୍ତୁ', newChat:'ନୂଆ ଚାଟ୍', language:'ଭାଷା', readAloudOn:'ଉଚ୍ଚ ସ୍ୱରରେ ପଢ଼ନ୍ତୁ: ଚାଲୁ', readAloudOff:'ଉଚ୍ଚ ସ୍ୱରରେ ପଢ଼ନ୍ତୁ: ବନ୍ଦ', suggested:'ପରାମର୍ଶିତ ପ୍ରଶ୍ନ', cropAdvice:'ଫସଲ ପରାମର୍ଶ', irrigation:'ଜଳସେଚନ', pest:'କୀଟ ଓ ରୋଗ', weather:'ପାଣିପାଗ', market:'ବଜାର', previousChats:'ପୂର୍ବ ଚାଟ୍', noChats:'କୌଣସି ସଞ୍ଚିତ କଥାବାର୍ତ୍ତା ନାହିଁ।', farmAware:'ଚାଷ-ଆଧାରିତ AI', processing:'ପ୍ରକ୍ରିୟା ଚାଲିଛି', listening:'ଶୁଣୁଛି', temporarilyUnavailable:'ଉଝାଭାନ AI ସାମୟିକ ଭାବେ ଉପଲବ୍ଧ ନାହିଁ', unavailableDesc:'ଏବେ ଉତ୍ତର ପ୍ରସ୍ତୁତ କରିପାରିଲୁ ନାହିଁ। ଆପଣଙ୍କ ଚାଷ ତଥ୍ୟ ସୁରକ୍ଷିତ ଅଛି। କିଛି ସମୟ ପରେ ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।', tryAgain:'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ', farmDataSafe:'ଆପଣଙ୍କ ଚାଷ ତଥ୍ୟ ସୁରକ୍ଷିତ ଅଛି।', profileTip:'ବ୍ୟକ୍ତିଗତ ପରାମର୍ଶ ପାଇଁ ଆପଣଙ୍କ କୃଷକ ପ୍ରୋଫାଇଲ୍ ପୂରଣ କରନ୍ତୁ।', askPlaceholder:'ଉଝାଭାନ AIକୁ କିଛି ବି ପଚାରନ୍ତୁ…'},
  ur: {...EN, assistant:'اُژوان AI', online:'آن لائن · AI زرعی معاون', subtitle:'اپنی فصل، مٹی، موسم، کیڑوں، آبپاشی، بازار کی قیمتوں اور کھیتی کے کاموں کے بارے میں پوچھیں۔', start:'گفتگو شروع کریں', askAnything:'اپنے کھیت کے بارے میں کچھ بھی پوچھیں', newChat:'نئی چیٹ', language:'زبان', readAloudOn:'بلند آواز میں پڑھیں: آن', readAloudOff:'بلند آواز میں پڑھیں: آف', suggested:'تجویز کردہ سوالات', cropAdvice:'فصل کا مشورہ', irrigation:'آبپاشی', pest:'کیڑے اور بیماریاں', weather:'موسم', market:'بازار', previousChats:'پچھلی چیٹس', noChats:'ابھی کوئی محفوظ گفتگو نہیں ہے۔', farmAware:'کھیت پر مبنی AI', processing:'پروسیسنگ جاری ہے', listening:'سن رہا ہے', temporarilyUnavailable:'اُژوان AI عارضی طور پر دستیاب نہیں', unavailableDesc:'اس وقت جواب تیار نہیں ہو سکا۔ آپ کے کھیت کا ڈیٹا محفوظ ہے۔ کچھ دیر بعد دوبارہ کوشش کریں۔', tryAgain:'دوبارہ کوشش کریں', farmDataSafe:'آپ کے کھیت کا ڈیٹا محفوظ ہے۔', profileTip:'ذاتی مشورے کے لیے اپنا کسان پروفائل مکمل کریں۔', askPlaceholder:'اُژوان AI سے کچھ بھی پوچھیں…'},
};

// Complete the scheduled-language set so the AI surface never falls back to English.
copies.as = {...EN, assistant:'উজাভান AI', online:'অনলাইন · AI কৃষি সহায়ক', start:'কথোপকথন শুরু করুন', askAnything:'আপোনাৰ খেতিৰ বিষয়ে যিকোনো কথা সোধক', newChat:'নতুন চেট', language:'ভাষা', readAloudOn:'জোৰেৰে পঢ়া: অন', readAloudOff:'জোৰেৰে পঢ়া: অফ', suggested:'পৰামৰ্শিত প্ৰশ্ন', cropAdvice:'শস্য পৰামৰ্শ', irrigation:'জলসিঞ্চন', pest:'কীট-পতংগ আৰু ৰোগ', weather:'বতৰ', market:'বজাৰ', previousChats:'পূৰ্বৰ চেট', noChats:'কোনো সংৰক্ষিত কথোপকথন নাই।', temporarilyUnavailable:'উজাভান AI সাময়িকভাৱে উপলব্ধ নহয়', unavailableDesc:'এতিয়া উত্তৰ সৃষ্টি কৰিব পৰা নগ’ল। আপোনাৰ খেতিৰ তথ্য সুৰক্ষিত। কিছু সময়ৰ পিছত পুনৰ চেষ্টা কৰক।', tryAgain:'পুনৰ চেষ্টা কৰক', farmDataSafe:'আপোনাৰ খেতিৰ তথ্য সুৰক্ষিত।', profileTip:'ব্যক্তিগত পৰামৰ্শৰ বাবে আপোনাৰ কৃষক প্ৰ’ফাইল সম্পূৰ্ণ কৰক।', askPlaceholder:'উজাভান AI-ক যিকোনো কথা সোধক…'};
copies.bodo = {...EN, assistant:'उजावन AI', online:'अनलाइन · AI कृषि सहायक', start:'गप सुरू खालाम', askAnything:'नोंथांनि फार्मनि सोमोन्दै जायखि सों', newChat:'गोदान चाट', language:'राव', suggested:'सोंनाय सोंफिनाय', cropAdvice:'फसल सल्ला', irrigation:'सिंचाइ', pest:'पोक-पोकानि आरो रोग', weather:'मौसम', market:'बाजार', previousChats:'गुबुन चाट', noChats:'जेबो सेव खालामनाय गप नङा।', temporarilyUnavailable:'उजावन AI दा समायिक बायदि उपलब्ध नङा', unavailableDesc:'दा जोबोद सोंलुं होनो हायाखै। नोंथांनि फार्म डाटा रैखा। थारै सानो उनाव फिन नाजा।', tryAgain:'फिन नाजा', farmDataSafe:'नोंथांनि फार्म डाटा रैखा।', profileTip:'गोनां सल्ला होनायनि थाखाय फार्म प्रोफाइल जोबोद खालाम।', askPlaceholder:'उजावन AI-जों जायखि सों…'};
copies.dogri = {...EN, assistant:'उझावन AI', online:'ऑनलाइन · AI कृषि सहायक', start:'गल्लबात शुरू करो', askAnything:'अपने खेत दे बारे च कुछ बी पुछो', newChat:'नमीं चैट', language:'भाशा', suggested:'सुझाए दे सवाल', cropAdvice:'फसल सलाह', irrigation:'सिंचाई', pest:'कीड़ ते रोग', weather:'मौसम', market:'बजार', previousChats:'पिछली चैटां', noChats:'अजे कोई संभाषण सेव नेईं।', temporarilyUnavailable:'उझावन AI अस्थायी तौर पर उपलब्ध नेईं', unavailableDesc:'हुन जवाब तैयार नेईं होई सकेआ। तुंदे खेत दा डेटा सुरक्षित ऐ। थोड़ी देर बाद फ्ही कोशिश करो।', tryAgain:'फ्ही कोशिश करो', farmDataSafe:'तुंदे खेत दा डेटा सुरक्षित ऐ।', profileTip:'निजी सलाह लेई किसान प्रोफाइल पूरा करो।', askPlaceholder:'उझावन AI गी कुछ बी पुछो…'};
copies.ks = {...EN, assistant:'اُژاون AI', online:'آن لائن · AI زرعی معاون', start:'بات چیت شروع کٔرِو', askAnything:'پنٕنہِ کھٲتِرۍ متعلق کُنہِ تہِ پٲٹھۍ پُچھِو', newChat:'نَو چیٹ', language:'زبان', suggested:'مشورہ دِنہٕ آمٕت سوال', cropAdvice:'فصل مشورہ', irrigation:'آبپاشی', pest:'کیڑے تہٕ بیماری', weather:'موسم', market:'بازار', previousChats:'پتہٕ چلاوِت چیٹ', noChats:'کُنہِ محفوظ گفتگو چھِ نہٕ۔', temporarilyUnavailable:'اُژاون AI فی الحال دستیاب چھِ نہٕ', unavailableDesc:'وُچھ نہٕ جواب تیار کٔرِتھ۔ تُہند کھٲتِرۍ ڈاٹا محفوظ چھُ۔ تھوڑی دیر پتہٕ دوبارہ کوشش کٔرِو۔', tryAgain:'دوبارہ کوشش کٔرِو', farmDataSafe:'تُہند کھٲتِرۍ ڈاٹا محفوظ چھُ۔', profileTip:'ذاتی مشورہٕ خٲطرٕ پنُن کسان پروفائل مکمل کٔرِو۔', askPlaceholder:'اُژاون AI سُنٛد کُنہِ تہِ پُچھِو…'};
copies.kok = {...EN, assistant:'उझावन AI', online:'ऑनलाइन · AI शेती सहाय्यक', start:'संवाद सुरू करात', askAnything:'तुमच्या शेताबद्दल कितेंय विचारात', newChat:'नवो चॅट', language:'भाशा', suggested:'सुचयलेले प्रस्न', cropAdvice:'पीक सल्लो', irrigation:'सिंचन', pest:'किडे आनी रोग', weather:'हवामान', market:'बाजार', previousChats:'पयलीं चॅट्स', noChats:'जतन केल्ले संवाद नात.', temporarilyUnavailable:'उझावन AI तात्पुरतो उपलब्ध ना', unavailableDesc:'आत्ता जाप तयार जावंक ना। तुमच्या शेताची माहिती सुरक्षित आसा। थोड्या वेळान परत प्रयत्न करात.', tryAgain:'परत प्रयत्न करात', farmDataSafe:'तुमच्या शेताची माहिती सुरक्षित आसा.', profileTip:'खास सल्ल्या खातीर शेतकरी प्रोफाइल पूर्ण करात.', askPlaceholder:'उझावन AI कायतरी विचारात…'};
copies.mai = {...EN, assistant:'उझावन AI', online:'ऑनलाइन · AI कृषि सहायक', start:'बातचीत शुरू करू', askAnything:'अपन खेतक बारेमे किछु पुछू', newChat:'नव चैट', language:'भाषा', suggested:'सुझाओल प्रश्न', cropAdvice:'फसल सलाह', irrigation:'सिंचाई', pest:'कीड़ा आ रोग', weather:'मौसम', market:'बजार', previousChats:'पछिला चैट', noChats:'अखन कोनो बातचीत सुरक्षित नहि अछि।', temporarilyUnavailable:'उझावन AI एखन अस्थायी रूपसँ उपलब्ध नहि अछि', unavailableDesc:'एखन उत्तर नहि बनि सकल। अहाँक खेतक डेटा सुरक्षित अछि। किछु देर बाद फेर कोशिश करू।', tryAgain:'फेर कोशिश करू', farmDataSafe:'अहाँक खेतक डेटा सुरक्षित अछि।', profileTip:'व्यक्तिगत सलाह लेल किसान प्रोफाइल पूरा करू।', askPlaceholder:'उझावन AI सँ किछु पुछू…'};
copies.mni = {...EN, assistant:'উঝাৱান AI', online:'অনলাইন · AI কৃষি সহায়ক', start:'ৱাৰ্তা আৰম্ভ কৰক', askAnything:'আপোনাৰ খেতিৰ বিষয়ে যিকোনো কথা সোধক', newChat:'নতুন চেট', language:'ভাষা', suggested:'পৰামৰ্শিত প্ৰশ্ন', cropAdvice:'শস্য পৰামৰ্শ', irrigation:'জলসিঞ্চন', pest:'কীট আৰু ৰোগ', weather:'বতৰ', market:'বজাৰ', previousChats:'পূৰ্বৰ চেট', noChats:'কোনো সংৰক্ষিত কথোপকথন নাই।', temporarilyUnavailable:'উঝাৱান AI সাময়িকভাৱে উপলব্ধ নহয়', unavailableDesc:'এতিয়া উত্তৰ সৃষ্টি কৰিব পৰা নগ’ল। আপোনাৰ খেতিৰ তথ্য সুৰক্ষিত। কিছু সময়ৰ পিছত পুনৰ চেষ্টা কৰক।', tryAgain:'পুনৰ চেষ্টা কৰক', farmDataSafe:'আপোনাৰ খেতিৰ তথ্য সুৰক্ষিত।', profileTip:'ব্যক্তিগত পৰামৰ্শৰ বাবে কৃষক প্ৰফাইল সম্পূৰ্ণ কৰক।', askPlaceholder:'উঝাৱান AI-ক যিকোনো কথা সোধক…'};
copies.ne = {...EN, assistant:'उझावन AI', online:'अनलाइन · AI कृषि सहायक', start:'कुराकानी सुरु गर्नुहोस्', askAnything:'आफ्नो खेतबारे जे पनि सोध्नुहोस्', newChat:'नयाँ च्याट', language:'भाषा', suggested:'सुझाइएका प्रश्नहरू', cropAdvice:'बाली सल्लाह', irrigation:'सिँचाइ', pest:'कीरा र रोग', weather:'मौसम', market:'बजार', previousChats:'अघिल्ला च्याटहरू', noChats:'कुनै सुरक्षित कुराकानी छैन।', temporarilyUnavailable:'उझावन AI अहिले अस्थायी रूपमा उपलब्ध छैन', unavailableDesc:'अहिले उत्तर तयार गर्न सकिएन। तपाईंको खेतको डेटा सुरक्षित छ। केही समयपछि फेरि प्रयास गर्नुहोस्।', tryAgain:'फेरि प्रयास गर्नुहोस्', farmDataSafe:'तपाईंको खेतको डेटा सुरक्षित छ।', profileTip:'व्यक्तिगत सल्लाहका लागि किसान प्रोफाइल पूरा गर्नुहोस्।', askPlaceholder:'उझावन AI लाई जे पनि सोध्नुहोस्…'};
copies.sa = {...EN, assistant:'उझावन AI', online:'सञ्जालस्थः · AI कृषिसहायकः', start:'संवादं प्रारभत', askAnything:'स्वक्षेत्रस्य विषये किमपि पृच्छत', newChat:'नूतनः संवादः', language:'भाषा', suggested:'सुझाविताः प्रश्नाः', cropAdvice:'सस्यपरामर्शः', irrigation:'सिञ्चनम्', pest:'कीट-रोगाः', weather:'वातावरणम्', market:'बाजारः', previousChats:'पूर्वसंवादाः', noChats:'सुरक्षिताः संवादाः न सन्ति।', temporarilyUnavailable:'उझावन AI अस्थायिरूपेण अनुपलब्धः', unavailableDesc:'अधुना उत्तरं निर्मातुं न शक्यते। भवतः क्षेत्रदत्तांशः सुरक्षितः अस्ति। किञ्चित् समयानन्तरं पुनः प्रयत्नं कुरुत।', tryAgain:'पुनः प्रयत्नं कुरुत', farmDataSafe:'भवतः क्षेत्रदत्तांशः सुरक्षितः अस्ति।', profileTip:'व्यक्तिगतपरामर्शाय कृषकप्रोफाइलं पूर्णं कुरुत।', askPlaceholder:'उझावन AI इत्यस्मै किमपि पृच्छत…'};
copies.sat = {...EN, assistant:'ᱩᱡᱷᱟᱵᱟᱱ AI', online:'ᱚᱱᱞᱟᱭᱤᱱ · AI ᱪᱟᱥ ᱥᱟᱦᱟᱭᱤ', start:'ᱜᱟᱯ ᱮᱦᱚᱵ ᱢᱮ', askAnything:'ᱟᱢᱟᱜ ᱪᱟᱥ ᱵᱟᱵᱚᱛ ᱡᱟᱦᱟᱱ ᱯᱟᱹᱛᱤ ᱯᱟᱹᱛᱤ ᱯᱟᱹᱪᱷᱟᱹᱣ ᱢᱮ', newChat:'ᱱᱟᱶᱟ ᱪᱟᱴ', language:'ᱯᱟᱹᱨᱥᱤ', suggested:'ᱥᱩᱡᱟᱹᱣ ᱯᱟᱹᱪᱷᱟᱹᱣ', cropAdvice:'ᱪᱟᱥ ᱥᱟᱦᱟᱭ', irrigation:'ᱥᱮᱪ', pest:'ᱠᱤᱲ ᱟᱨ ᱨᱩᱜ', weather:'ᱦᱟᱣᱟ', market:'ᱵᱟᱡᱟᱨ', previousChats:'ᱞᱟᱦᱟ ᱪᱟᱴ', noChats:'ᱡᱟᱦᱟᱱ ᱥᱟᱵᱟᱨ ᱜᱟᱯ ᱵᱟᱝ ᱢᱮᱱᱟᱜᱼᱟ', temporarilyUnavailable:'ᱩᱡᱷᱟᱵᱟᱱ AI ᱛᱟᱭᱚᱢ ᱵᱟᱝ ᱢᱮᱱᱟᱜᱼᱟ', unavailableDesc:'ᱱᱤᱛᱚᱜ ᱡᱟᱹᱣᱟᱵ ᱵᱟᱝ ᱵᱟᱱᱟᱣ ᱦᱚᱭᱚᱜᱼᱟ। ᱟᱢᱟᱜ ᱪᱟᱥ ᱰᱟᱴᱟ ᱡᱟᱹᱯᱟᱹᱱ ᱢᱮᱱᱟᱜᱼᱟ। ᱠᱤᱪᱷᱩ ᱥᱟᱢᱟᱭ ᱛᱟᱭᱚᱢ ᱫᱚᱦᱲᱟ ᱪᱮᱫ ᱢᱮ।', tryAgain:'ᱫᱚᱦᱲᱟ ᱪᱮᱫ ᱢᱮ', farmDataSafe:'ᱟᱢᱟᱜ ᱪᱟᱥ ᱰᱟᱴᱟ ᱡᱟᱹᱯᱟᱹᱱ ᱢᱮᱱᱟᱜᱼᱟ', profileTip:'ᱱᱤᱡᱮᱨ ᱥᱟᱦᱟᱭ ᱞᱟᱹᱜᱤᱫ ᱪᱟᱥᱤ ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱯᱩᱨᱟᱹ ᱢᱮ', askPlaceholder:'ᱩᱡᱷᱟᱵᱟᱱ AI ᱠᱟᱹᱛᱮ ᱡᱟᱦᱟᱱ ᱯᱟᱹᱪᱷᱟᱹᱣ ᱢᱮ…'};
copies.sd = {...EN, assistant:'اُجھاون AI', online:'آن لائن · AI زرعي مددگار', start:'ڳالهه ٻولهه شروع ڪريو', askAnything:'پنهنجي کيت بابت ڪجهه به پڇو', newChat:'نئين چيٽ', language:'ٻولي', suggested:'تجويز ڪيل سوال', cropAdvice:'فصل صلاح', irrigation:'آبپاشي', pest:'جيت ۽ بيماري', weather:'موسم', market:'بازار', previousChats:'اڳيون چيٽ', noChats:'اڃا ڪا محفوظ ڳالهه ٻولهه ناهي۔', temporarilyUnavailable:'اُجھاون AI عارضي طور دستياب ناهي', unavailableDesc:'هن وقت جواب تيار نه ٿي سگهيو۔ توهان جي کيت جو ڊيٽا محفوظ آهي۔ ٿوري دير کان پوءِ ٻيهر ڪوشش ڪريو۔', tryAgain:'ٻيهر ڪوشش ڪريو', farmDataSafe:'توهان جي کيت جو ڊيٽا محفوظ آهي۔', profileTip:'ذاتي صلاح لاءِ پنهنجو هاري پروفائل مڪمل ڪريو۔', askPlaceholder:'اُجھاون AI کان ڪجهه به پڇو…'};

export function getAiCopy(language: string): AiCopy {
  return copies[language] ?? EN;
}
