export type UiLanguage = string;

// Core UI vocabulary used across authentication, navigation, farm setup and common states.
// Feature-specific copy should be added to the same catalog instead of hard-coding strings.
export const UI_TRANSLATIONS: Record<UiLanguage, Record<string, string>> = {
  en: {
    'Dashboard':'Dashboard','Farm Intelligence':'Farm Intelligence','Farm Health':'Farm Health','My Farm':'My Farm','Farmer Memory':'Farmer Memory','Daily Farm Plan':'Daily Farm Plan','Crop Lifecycle':'Crop Lifecycle','Crop Health':'Crop Health','Crop Recommendation':'Crop Recommendation','Yield Prediction':'Yield Prediction','Weather':'Weather','Market Intelligence':'Market Intelligence','Smart Alerts':'Smart Alerts','AI Assistant':'AI Assistant','Government Schemes':'Government Schemes','Marketplace':'Marketplace','Notifications':'Notifications','Expense Tracker':'Expense Tracker','Analytics':'Analytics','Farm Report':'Farm Report','Season Report':'Season Report','Offline Mode':'Offline Mode','Profile':'Profile','Settings':'Settings','Sign in':'Sign in','Sign up':'Sign up','Login':'Login','Logout':'Logout','Save':'Save','Cancel':'Cancel','Continue':'Continue','Back':'Back','Search':'Search','Loading…':'Loading…','Loading...':'Loading...','Error':'Error','Retry':'Retry','Close':'Close','Edit':'Edit','Delete':'Delete','Add':'Add','Submit':'Submit','Name':'Name','Email address':'Email address','Password':'Password','Full name':'Full name','Location':'Location','Farm size':'Farm size','Soil type':'Soil type','Irrigation method':'Irrigation method','Current crop':'Current crop','Crop stage':'Crop stage','Save & Continue':'Save & Continue','Choose your language':'Choose your language','Choose your role':'Choose your role','I’m a Farmer':'I’m a Farmer','I’m a Visitor':'I’m a Visitor','Set up your farm':'Set up your farm','Go to Dashboard':'Go to Dashboard','Welcome back':'Welcome back'
  },
  hi: {
    'Dashboard':'डैशबोर्ड','Farm Intelligence':'कृषि बुद्धिमत्ता','Farm Health':'खेत का स्वास्थ्य','My Farm':'मेरा खेत','Farmer Memory':'किसान प्रोफ़ाइल','Daily Farm Plan':'दैनिक कृषि योजना','Crop Lifecycle':'फसल जीवनचक्र','Crop Health':'फसल स्वास्थ्य','Crop Recommendation':'फसल अनुशंसा','Yield Prediction':'उपज पूर्वानुमान','Weather':'मौसम','Market Intelligence':'बाज़ार बुद्धिमत्ता','Smart Alerts':'स्मार्ट अलर्ट','AI Assistant':'AI सहायक','Government Schemes':'सरकारी योजनाएँ','Marketplace':'बाज़ार','Notifications':'सूचनाएँ','Expense Tracker':'खर्च ट्रैकर','Analytics':'विश्लेषण','Farm Report':'खेत रिपोर्ट','Season Report':'सीज़न रिपोर्ट','Offline Mode':'ऑफ़लाइन मोड','Profile':'प्रोफ़ाइल','Settings':'सेटिंग्स','Sign in':'लॉग इन करें','Sign up':'साइन अप करें','Login':'लॉग इन','Logout':'लॉग आउट','Save':'सहेजें','Cancel':'रद्द करें','Continue':'जारी रखें','Back':'वापस','Search':'खोजें','Loading…':'लोड हो रहा है…','Loading...':'लोड हो रहा है...','Error':'त्रुटि','Retry':'फिर प्रयास करें','Close':'बंद करें','Edit':'संपादित करें','Delete':'हटाएँ','Add':'जोड़ें','Submit':'जमा करें','Name':'नाम','Email address':'ईमेल पता','Password':'पासवर्ड','Full name':'पूरा नाम','Location':'स्थान','Farm size':'खेत का क्षेत्रफल','Soil type':'मिट्टी का प्रकार','Irrigation method':'सिंचाई विधि','Current crop':'वर्तमान फसल','Crop stage':'फसल की अवस्था','Save & Continue':'सहेजें और जारी रखें','Choose your language':'अपनी भाषा चुनें','Choose your role':'अपनी भूमिका चुनें','I’m a Farmer':'मैं किसान हूँ','I’m a Visitor':'मैं आगंतुक हूँ','Set up your farm':'अपना खेत सेट करें','Go to Dashboard':'डैशबोर्ड पर जाएँ','Welcome back':'वापसी पर स्वागत है'
  },
  ta: {
    'Dashboard':'டாஷ்போர்டு','Farm Intelligence':'பண்ணை நுண்ணறிவு','Farm Health':'பண்ணை ஆரோக்கியம்','My Farm':'என் பண்ணை','Farmer Memory':'விவசாயி சுயவிவரம்','Daily Farm Plan':'தினசரி பண்ணைத் திட்டம்','Crop Lifecycle':'பயிர் வாழ்க்கைச் சுழற்சி','Crop Health':'பயிர் ஆரோக்கியம்','Crop Recommendation':'பயிர் பரிந்துரை','Yield Prediction':'மகசூல் கணிப்பு','Weather':'வானிலை','Market Intelligence':'சந்தை நுண்ணறிவு','Smart Alerts':'ஸ்மார்ட் எச்சரிக்கைகள்','AI Assistant':'AI உதவியாளர்','Government Schemes':'அரசுத் திட்டங்கள்','Marketplace':'சந்தை','Notifications':'அறிவிப்புகள்','Expense Tracker':'செலவு கண்காணிப்பு','Analytics':'பகுப்பாய்வு','Farm Report':'பண்ணை அறிக்கை','Season Report':'பருவ அறிக்கை','Offline Mode':'ஆஃப்லைன் பயன்முறை','Profile':'சுயவிவரம்','Settings':'அமைப்புகள்','Sign in':'உள்நுழைக','Sign up':'பதிவு செய்க','Login':'உள்நுழைவு','Logout':'வெளியேறு','Save':'சேமி','Cancel':'ரத்து செய்','Continue':'தொடரவும்','Back':'பின்செல்','Search':'தேடு','Loading…':'ஏற்றப்படுகிறது…','Loading...':'ஏற்றப்படுகிறது...','Error':'பிழை','Retry':'மீண்டும் முயற்சி','Close':'மூடு','Edit':'திருத்து','Delete':'நீக்கு','Add':'சேர்','Submit':'சமர்ப்பி','Name':'பெயர்','Email address':'மின்னஞ்சல் முகவரி','Password':'கடவுச்சொல்','Full name':'முழுப் பெயர்','Location':'இடம்','Farm size':'பண்ணை அளவு','Soil type':'மண் வகை','Irrigation method':'நீர்ப்பாசன முறை','Current crop':'தற்போதைய பயிர்','Crop stage':'பயிர் நிலை','Save & Continue':'சேமித்து தொடரவும்','Choose your language':'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்','Choose your role':'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்','I’m a Farmer':'நான் விவசாயி','I’m a Visitor':'நான் பார்வையாளர்','Set up your farm':'உங்கள் பண்ணையை அமைக்கவும்','Go to Dashboard':'டாஷ்போர்டுக்குச் செல்லவும்','Welcome back':'மீண்டும் வரவேற்கிறோம்'
  },
  te: {
    'Dashboard':'డ్యాష్‌బోర్డ్','Farm Intelligence':'వ్యవసాయ మేధస్సు','Farm Health':'పొలం ఆరోగ్యం','My Farm':'నా పొలం','Farmer Memory':'రైతు ప్రొఫైల్','Daily Farm Plan':'రోజువారీ వ్యవసాయ ప్రణాళిక','Crop Lifecycle':'పంట జీవచక్రం','Crop Health':'పంట ఆరోగ్యం','Crop Recommendation':'పంట సిఫార్సు','Yield Prediction':'దిగుబడి అంచనా','Weather':'వాతావరణం','Market Intelligence':'మార్కెట్ మేధస్సు','Smart Alerts':'స్మార్ట్ హెచ్చరికలు','AI Assistant':'AI సహాయకుడు','Government Schemes':'ప్రభుత్వ పథకాలు','Marketplace':'మార్కెట్','Notifications':'నోటిఫికేషన్లు','Expense Tracker':'ఖర్చుల ట్రాకర్','Analytics':'విశ్లేషణ','Farm Report':'పొలం నివేదిక','Season Report':'సీజన్ నివేదిక','Offline Mode':'ఆఫ్‌లైన్ మోడ్','Profile':'ప్రొఫైల్','Settings':'సెట్టింగ్‌లు','Sign in':'లాగిన్','Sign up':'సైన్ అప్','Login':'లాగిన్','Logout':'లాగ్ అవుట్','Save':'సేవ్ చేయండి','Cancel':'రద్దు చేయండి','Continue':'కొనసాగించండి','Back':'వెనక్కి','Search':'వెతకండి','Loading…':'లోడ్ అవుతోంది…','Loading...':'లోడ్ అవుతోంది...','Error':'లోపం','Retry':'మళ్లీ ప్రయత్నించండి','Close':'మూసివేయండి','Edit':'సవరించండి','Delete':'తొలగించండి','Add':'జోడించండి','Submit':'సమర్పించండి','Name':'పేరు','Email address':'ఇమెయిల్ చిరునామా','Password':'పాస్‌వర్డ్','Full name':'పూర్తి పేరు','Location':'స్థానం','Farm size':'పొలం పరిమాణం','Soil type':'నేల రకం','Irrigation method':'నీటిపారుదల విధానం','Current crop':'ప్రస్తుత పంట','Crop stage':'పంట దశ','Save & Continue':'సేవ్ చేసి కొనసాగించండి','Choose your language':'మీ భాషను ఎంచుకోండి','Choose your role':'మీ పాత్రను ఎంచుకోండి','I’m a Farmer':'నేను రైతును','I’m a Visitor':'నేను సందర్శకుడిని','Set up your farm':'మీ పొలాన్ని ఏర్పాటు చేయండి','Go to Dashboard':'డ్యాష్‌బోర్డ్‌కు వెళ్లండి','Welcome back':'తిరిగి స్వాగతం'
  },
  ml: {
    'Dashboard':'ഡാഷ്ബോർഡ്','Farm Intelligence':'കൃഷി ബുദ്ധി','Farm Health':'കൃഷിയിട ആരോഗ്യം','My Farm':'എന്റെ കൃഷിയിടം','Farmer Memory':'കർഷക പ്രൊഫൈൽ','Daily Farm Plan':'ദൈനംദിന കൃഷി പദ്ധതി','Crop Lifecycle':'വിള ജീവിതചക്രം','Crop Health':'വിള ആരോഗ്യം','Crop Recommendation':'വിള ശുപാർശ','Yield Prediction':'വിളവ് പ്രവചനം','Weather':'കാലാവസ്ഥ','Market Intelligence':'വിപണി ബുദ്ധി','Smart Alerts':'സ്മാർട്ട് അലർട്ടുകൾ','AI Assistant':'AI സഹായി','Government Schemes':'സർക്കാർ പദ്ധതികൾ','Marketplace':'വിപണി','Notifications':'അറിയിപ്പുകൾ','Expense Tracker':'ചെലവ് ട്രാക്കർ','Analytics':'വിശകലനം','Farm Report':'കൃഷിയിട റിപ്പോർട്ട്','Season Report':'സീസൺ റിപ്പോർട്ട്','Offline Mode':'ഓഫ്‌ലൈൻ മോഡ്','Profile':'പ്രൊഫൈൽ','Settings':'ക്രമീകരണങ്ങൾ','Sign in':'ലോഗിൻ ചെയ്യുക','Sign up':'സൈൻ അപ്പ് ചെയ്യുക','Login':'ലോഗിൻ','Logout':'ലോഗൗട്ട്','Save':'സംരക്ഷിക്കുക','Cancel':'റദ്ദാക്കുക','Continue':'തുടരുക','Back':'പിന്നോട്ട്','Search':'തിരയുക','Loading…':'ലോഡ് ചെയ്യുന്നു…','Loading...':'ലോഡ് ചെയ്യുന്നു...','Error':'പിശക്','Retry':'വീണ്ടും ശ്രമിക്കുക','Close':'അടയ്ക്കുക','Edit':'തിരുത്തുക','Delete':'ഇല്ലാതാക്കുക','Add':'ചേർക്കുക','Submit':'സമർപ്പിക്കുക','Name':'പേര്','Email address':'ഇമെയിൽ വിലാസം','Password':'പാസ്‌വേഡ്','Full name':'പൂർണ്ണ പേര്','Location':'സ്ഥലം','Farm size':'കൃഷിയിടത്തിന്റെ വലുപ്പം','Soil type':'മണ്ണിന്റെ തരം','Irrigation method':'ജലസേചന രീതി','Current crop':'നിലവിലെ വിള','Crop stage':'വിളയുടെ ഘട്ടം','Save & Continue':'സംരക്ഷിച്ച് തുടരുക','Choose your language':'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക','Choose your role':'നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക','I’m a Farmer':'ഞാൻ കർഷകനാണ്','I’m a Visitor':'ഞാൻ സന്ദർശകനാണ്','Set up your farm':'നിങ്ങളുടെ കൃഷിയിടം സജ്ജമാക്കുക','Go to Dashboard':'ഡാഷ്ബോർഡിലേക്ക് പോകുക','Welcome back':'തിരികെ സ്വാഗതം'
  },
  kn: {
    'Dashboard':'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್','Farm Intelligence':'ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ','Farm Health':'ಕೃಷಿ ಆರೋಗ್ಯ','My Farm':'ನನ್ನ ಕೃಷಿ','Farmer Memory':'ರೈತ ಪ್ರೊಫೈಲ್','Daily Farm Plan':'ದೈನಂದಿನ ಕೃಷಿ ಯೋಜನೆ','Crop Lifecycle':'ಬೆಳೆ ಜೀವನಚಕ್ರ','Crop Health':'ಬೆಳೆ ಆರೋಗ್ಯ','Crop Recommendation':'ಬೆಳೆ ಶಿಫಾರಸು','Yield Prediction':'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ','Weather':'ಹವಾಮಾನ','Market Intelligence':'ಮಾರುಕಟ್ಟೆ ಬುದ್ಧಿಮತ್ತೆ','Smart Alerts':'ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆಗಳು','AI Assistant':'AI ಸಹಾಯಕ','Government Schemes':'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು','Marketplace':'ಮಾರುಕಟ್ಟೆ','Notifications':'ಅಧಿಸೂಚನೆಗಳು','Expense Tracker':'ವೆಚ್ಚ ಟ್ರ್ಯಾಕರ್','Analytics':'ವಿಶ್ಲೇಷಣೆ','Farm Report':'ಕೃಷಿ ವರದಿ','Season Report':'ಋತು ವರದಿ','Offline Mode':'ಆಫ್‌ಲೈನ್ ಮೋಡ್','Profile':'ಪ್ರೊಫೈಲ್','Settings':'ಸೆಟ್ಟಿಂಗ್‌ಗಳು','Sign in':'ಲಾಗಿನ್','Sign up':'ಸೈನ್ ಅಪ್','Login':'ಲಾಗಿನ್','Logout':'ಲಾಗ್ ಔಟ್','Save':'ಉಳಿಸಿ','Cancel':'ರದ್ದುಮಾಡಿ','Continue':'ಮುಂದುವರಿಸಿ','Back':'ಹಿಂದಕ್ಕೆ','Search':'ಹುಡುಕಿ','Loading…':'ಲೋಡ್ ಆಗುತ್ತಿದೆ…','Loading...':'ಲೋಡ್ ಆಗುತ್ತಿದೆ...','Error':'ದೋಷ','Retry':'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ','Close':'ಮುಚ್ಚಿ','Edit':'ತಿದ್ದು','Delete':'ಅಳಿಸಿ','Add':'ಸೇರಿಸಿ','Submit':'ಸಲ್ಲಿಸಿ','Name':'ಹೆಸರು','Email address':'ಇಮೇಲ್ ವಿಳಾಸ','Password':'ಪಾಸ್‌ವರ್ಡ್','Full name':'ಪೂರ್ಣ ಹೆಸರು','Location':'ಸ್ಥಳ','Farm size':'ಕೃಷಿ ಗಾತ್ರ','Soil type':'ಮಣ್ಣಿನ ವಿಧ','Irrigation method':'ನೀರಾವರಿ ವಿಧಾನ','Current crop':'ಪ್ರಸ್ತುತ ಬೆಳೆ','Crop stage':'ಬೆಳೆ ಹಂತ','Save & Continue':'ಉಳಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ','Choose your language':'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ','Choose your role':'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ','I’m a Farmer':'ನಾನು ರೈತ','I’m a Visitor':'ನಾನು ಸಂದರ್ಶಕ','Set up your farm':'ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ಹೊಂದಿಸಿ','Go to Dashboard':'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ','Welcome back':'ಮತ್ತೆ ಸ್ವಾಗತ'
  },
  bn: {
    'Dashboard':'ড্যাশবোর্ড','Farm Intelligence':'কৃষি বুদ্ধিমত্তা','Farm Health':'খামারের স্বাস্থ্য','My Farm':'আমার খামার','Farmer Memory':'কৃষক প্রোফাইল','Daily Farm Plan':'দৈনিক কৃষি পরিকল্পনা','Crop Lifecycle':'ফসলের জীবনচক্র','Crop Health':'ফসলের স্বাস্থ্য','Crop Recommendation':'ফসলের সুপারিশ','Yield Prediction':'ফলন পূর্বাভাস','Weather':'আবহাওয়া','Market Intelligence':'বাজার বুদ্ধিমত্তা','Smart Alerts':'স্মার্ট সতর্কতা','AI Assistant':'AI সহায়ক','Government Schemes':'সরকারি প্রকল্প','Marketplace':'বাজার','Notifications':'বিজ্ঞপ্তি','Expense Tracker':'খরচ ট্র্যাকার','Analytics':'বিশ্লেষণ','Farm Report':'খামার প্রতিবেদন','Season Report':'মৌসুম প্রতিবেদন','Offline Mode':'অফলাইন মোড','Profile':'প্রোফাইল','Settings':'সেটিংস','Sign in':'লগ ইন করুন','Sign up':'সাইন আপ করুন','Login':'লগ ইন','Logout':'লগ আউট','Save':'সংরক্ষণ করুন','Cancel':'বাতিল করুন','Continue':'চালিয়ে যান','Back':'পিছনে','Search':'খুঁজুন','Loading…':'লোড হচ্ছে…','Loading...':'লোড হচ্ছে...','Error':'ত্রুটি','Retry':'আবার চেষ্টা করুন','Close':'বন্ধ করুন','Edit':'সম্পাদনা','Delete':'মুছুন','Add':'যোগ করুন','Submit':'জমা দিন','Name':'নাম','Email address':'ইমেল ঠিকানা','Password':'পাসওয়ার্ড','Full name':'পুরো নাম','Location':'অবস্থান','Farm size':'খামারের আকার','Soil type':'মাটির ধরন','Irrigation method':'সেচ পদ্ধতি','Current crop':'বর্তমান ফসল','Crop stage':'ফসলের পর্যায়','Save & Continue':'সংরক্ষণ করে চালিয়ে যান','Choose your language':'আপনার ভাষা নির্বাচন করুন','Choose your role':'আপনার ভূমিকা নির্বাচন করুন','I’m a Farmer':'আমি একজন কৃষক','I’m a Visitor':'আমি একজন দর্শনার্থী','Set up your farm':'আপনার খামার সেট আপ করুন','Go to Dashboard':'ড্যাশবোর্ডে যান','Welcome back':'আবার স্বাগতম'
  },
  mr: {
    'Dashboard':'डॅशबोर्ड','Farm Intelligence':'शेती बुद्धिमत्ता','Farm Health':'शेताचे आरोग्य','My Farm':'माझे शेत','Farmer Memory':'शेतकरी प्रोफाइल','Daily Farm Plan':'दैनंदिन शेती योजना','Crop Lifecycle':'पीक जीवनचक्र','Crop Health':'पीक आरोग्य','Crop Recommendation':'पीक शिफारस','Yield Prediction':'उत्पादन अंदाज','Weather':'हवामान','Market Intelligence':'बाजार बुद्धिमत्ता','Smart Alerts':'स्मार्ट सूचना','AI Assistant':'AI सहाय्यक','Government Schemes':'सरकारी योजना','Marketplace':'बाजार','Notifications':'सूचना','Expense Tracker':'खर्च ट्रॅकर','Analytics':'विश्लेषण','Farm Report':'शेत अहवाल','Season Report':'हंगाम अहवाल','Offline Mode':'ऑफलाइन मोड','Profile':'प्रोफाइल','Settings':'सेटिंग्ज','Sign in':'लॉग इन करा','Sign up':'साइन अप करा','Login':'लॉग इन','Logout':'लॉग आउट','Save':'जतन करा','Cancel':'रद्द करा','Continue':'पुढे चला','Back':'मागे','Search':'शोधा','Loading…':'लोड होत आहे…','Loading...':'लोड होत आहे...','Error':'त्रुटी','Retry':'पुन्हा प्रयत्न करा','Close':'बंद करा','Edit':'संपादित करा','Delete':'हटवा','Add':'जोडा','Submit':'सबमिट करा','Name':'नाव','Email address':'ईमेल पत्ता','Password':'पासवर्ड','Full name':'पूर्ण नाव','Location':'स्थान','Farm size':'शेताचे क्षेत्रफळ','Soil type':'मातीचा प्रकार','Irrigation method':'सिंचन पद्धत','Current crop':'सध्याचे पीक','Crop stage':'पिकाची अवस्था','Save & Continue':'जतन करा आणि पुढे चला','Choose your language':'तुमची भाषा निवडा','Choose your role':'तुमची भूमिका निवडा','I’m a Farmer':'मी शेतकरी आहे','I’m a Visitor':'मी पाहुणा आहे','Set up your farm':'तुमचे शेत सेट करा','Go to Dashboard':'डॅशबोर्डवर जा','Welcome back':'पुन्हा स्वागत आहे'
  },
  gu: {
    'Dashboard':'ડેશબોર્ડ','Farm Intelligence':'ખેતી બુદ્ધિ','Farm Health':'ખેતરનું આરોગ્ય','My Farm':'મારું ખેતર','Farmer Memory':'ખેડૂત પ્રોફાઇલ','Daily Farm Plan':'દૈનિક ખેતી યોજના','Crop Lifecycle':'પાક જીવનચક્ર','Crop Health':'પાક આરોગ્ય','Crop Recommendation':'પાક ભલામણ','Yield Prediction':'ઉપજ આગાહી','Weather':'હવામાન','Market Intelligence':'બજાર બુદ્ધિ','Smart Alerts':'સ્માર્ટ ચેતવણીઓ','AI Assistant':'AI સહાયક','Government Schemes':'સરકારી યોજનાઓ','Marketplace':'બજાર','Notifications':'સૂચનાઓ','Expense Tracker':'ખર્ચ ટ્રેકર','Analytics':'વિશ્લેષણ','Farm Report':'ખેતર અહેવાલ','Season Report':'મોસમ અહેવાલ','Offline Mode':'ઑફલાઇન મોડ','Profile':'પ્રોફાઇલ','Settings':'સેટિંગ્સ','Sign in':'લૉગ ઇન કરો','Sign up':'સાઇન અપ કરો','Login':'લૉગ ઇન','Logout':'લૉગ આઉટ','Save':'સાચવો','Cancel':'રદ કરો','Continue':'ચાલુ રાખો','Back':'પાછળ','Search':'શોધો','Loading…':'લોડ થઈ રહ્યું છે…','Loading...':'લોડ થઈ રહ્યું છે...','Error':'ભૂલ','Retry':'ફરી પ્રયાસ કરો','Close':'બંધ કરો','Edit':'ફેરફાર કરો','Delete':'કાઢી નાખો','Add':'ઉમેરો','Submit':'સબમિટ કરો','Name':'નામ','Email address':'ઇમેઇલ સરનામું','Password':'પાસવર્ડ','Full name':'પૂરું નામ','Location':'સ્થળ','Farm size':'ખેતરનું કદ','Soil type':'માટીનો પ્રકાર','Irrigation method':'સિંચાઈ પદ્ધતિ','Current crop':'વર્તમાન પાક','Crop stage':'પાકની અવસ્થા','Save & Continue':'સાચવો અને ચાલુ રાખો','Choose your language':'તમારી ભાષા પસંદ કરો','Choose your role':'તમારી ભૂમિકા પસંદ કરો','I’m a Farmer':'હું ખેડૂત છું','I’m a Visitor':'હું મુલાકાતી છું','Set up your farm':'તમારું ખેતર સેટ કરો','Go to Dashboard':'ડેશબોર્ડ પર જાઓ','Welcome back':'ફરી સ્વાગત છે'
  },
  pa: {
    'Dashboard':'ਡੈਸ਼ਬੋਰਡ','Farm Intelligence':'ਖੇਤੀਬਾੜੀ ਬੁੱਧੀ','Farm Health':'ਖੇਤ ਦੀ ਸਿਹਤ','My Farm':'ਮੇਰਾ ਖੇਤ','Farmer Memory':'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ','Daily Farm Plan':'ਰੋਜ਼ਾਨਾ ਖੇਤੀ ਯੋਜਨਾ','Crop Lifecycle':'ਫਸਲ ਜੀਵਨ ਚੱਕਰ','Crop Health':'ਫਸਲ ਸਿਹਤ','Crop Recommendation':'ਫਸਲ ਸਿਫਾਰਸ਼','Yield Prediction':'ਪੈਦਾਵਾਰ ਅਨੁਮਾਨ','Weather':'ਮੌਸਮ','Market Intelligence':'ਮੰਡੀ ਬੁੱਧੀ','Smart Alerts':'ਸਮਾਰਟ ਚੇਤਾਵਨੀਆਂ','AI Assistant':'AI ਸਹਾਇਕ','Government Schemes':'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ','Marketplace':'ਬਾਜ਼ਾਰ','Notifications':'ਸੂਚਨਾਵਾਂ','Expense Tracker':'ਖਰਚਾ ਟ੍ਰੈਕਰ','Analytics':'ਵਿਸ਼ਲੇਸ਼ਣ','Farm Report':'ਖੇਤ ਰਿਪੋਰਟ','Season Report':'ਸੀਜ਼ਨ ਰਿਪੋਰਟ','Offline Mode':'ਆਫਲਾਈਨ ਮੋਡ','Profile':'ਪ੍ਰੋਫਾਈਲ','Settings':'ਸੈਟਿੰਗਾਂ','Sign in':'ਲੌਗ ਇਨ ਕਰੋ','Sign up':'ਸਾਈਨ ਅੱਪ ਕਰੋ','Login':'ਲੌਗ ਇਨ','Logout':'ਲੌਗ ਆਉਟ','Save':'ਸੇਵ ਕਰੋ','Cancel':'ਰੱਦ ਕਰੋ','Continue':'ਜਾਰੀ ਰੱਖੋ','Back':'ਵਾਪਸ','Search':'ਖੋਜੋ','Loading…':'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…','Loading...':'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...','Error':'ਗਲਤੀ','Retry':'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ','Close':'ਬੰਦ ਕਰੋ','Edit':'ਸੋਧੋ','Delete':'ਮਿਟਾਓ','Add':'ਜੋੜੋ','Submit':'ਜਮ੍ਹਾਂ ਕਰੋ','Name':'ਨਾਮ','Email address':'ਈਮੇਲ ਪਤਾ','Password':'ਪਾਸਵਰਡ','Full name':'ਪੂਰਾ ਨਾਮ','Location':'ਸਥਾਨ','Farm size':'ਖੇਤ ਦਾ ਆਕਾਰ','Soil type':'ਮਿੱਟੀ ਦੀ ਕਿਸਮ','Irrigation method':'ਸਿੰਚਾਈ ਵਿਧੀ','Current crop':'ਮੌਜੂਦਾ ਫਸਲ','Crop stage':'ਫਸਲ ਦੀ ਅਵਸਥਾ','Save & Continue':'ਸੇਵ ਕਰਕੇ ਜਾਰੀ ਰੱਖੋ','Choose your language':'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ','Choose your role':'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ','I’m a Farmer':'ਮੈਂ ਕਿਸਾਨ ਹਾਂ','I’m a Visitor':'ਮੈਂ ਵਿਜ਼ਟਰ ਹਾਂ','Set up your farm':'ਆਪਣਾ ਖੇਤ ਸੈੱਟ ਕਰੋ','Go to Dashboard':'ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ','Welcome back':'ਜੀ ਆਇਆਂ ਨੂੰ ਵਾਪਸ'
  },
  or: {
    'Dashboard':'ଡ୍ୟାଶବୋର୍ଡ','Farm Intelligence':'କୃଷି ବୁଦ୍ଧିମତ୍ତା','Farm Health':'ଫାର୍ମ ସ୍ୱାସ୍ଥ୍ୟ','My Farm':'ମୋ ଫାର୍ମ','Farmer Memory':'କୃଷକ ପ୍ରୋଫାଇଲ୍','Daily Farm Plan':'ଦୈନିକ କୃଷି ଯୋଜନା','Crop Lifecycle':'ଫସଲ ଜୀବନଚକ୍ର','Crop Health':'ଫସଲ ସ୍ୱାସ୍ଥ୍ୟ','Crop Recommendation':'ଫସଲ ସୁପାରିଶ','Yield Prediction':'ଅମଳ ପୂର୍ବାନୁମାନ','Weather':'ପାଣିପାଗ','Market Intelligence':'ବଜାର ବୁଦ୍ଧିମତ୍ତା','Smart Alerts':'ସ୍ମାର୍ଟ ସତର୍କତା','AI Assistant':'AI ସହାୟକ','Government Schemes':'ସରକାରୀ ଯୋଜନା','Marketplace':'ବଜାର','Notifications':'ବିଜ୍ଞପ୍ତି','Expense Tracker':'ଖର୍ଚ୍ଚ ଟ୍ରାକର୍','Analytics':'ବିଶ୍ଳେଷଣ','Farm Report':'ଫାର୍ମ ରିପୋର୍ଟ','Season Report':'ଋତୁ ରିପୋର୍ଟ','Offline Mode':'ଅଫଲାଇନ୍ ମୋଡ୍','Profile':'ପ୍ରୋଫାଇଲ୍','Settings':'ସେଟିଂସ୍','Sign in':'ଲଗ୍ ଇନ୍ କରନ୍ତୁ','Sign up':'ସାଇନ୍ ଅପ୍ କରନ୍ତୁ','Login':'ଲଗ୍ ଇନ୍','Logout':'ଲଗ୍ ଆଉଟ୍','Save':'ସଞ୍ଚୟ କରନ୍ତୁ','Cancel':'ବାତିଲ୍ କରନ୍ତୁ','Continue':'ଜାରି ରଖନ୍ତୁ','Back':'ପଛକୁ','Search':'ଖୋଜନ୍ତୁ','Loading…':'ଲୋଡ୍ ହେଉଛି…','Loading...':'ଲୋଡ୍ ହେଉଛି...','Error':'ତ୍ରୁଟି','Retry':'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ','Close':'ବନ୍ଦ କରନ୍ତୁ','Edit':'ସମ୍ପାଦନ କରନ୍ତୁ','Delete':'ଡିଲିଟ୍ କରନ୍ତୁ','Add':'ଯୋଡନ୍ତୁ','Submit':'ଦାଖଲ କରନ୍ତୁ','Name':'ନାମ','Email address':'ଇମେଲ୍ ଠିକଣା','Password':'ପାସୱାର୍ଡ','Full name':'ପୂର୍ଣ୍ଣ ନାମ','Location':'ସ୍ଥାନ','Farm size':'ଫାର୍ମ ଆକାର','Soil type':'ମାଟି ପ୍ରକାର','Irrigation method':'ଜଳସେଚନ ପ୍ରଣାଳୀ','Current crop':'ବର୍ତ୍ତମାନ ଫସଲ','Crop stage':'ଫସଲ ପର୍ଯ୍ୟାୟ','Save & Continue':'ସଞ୍ଚୟ କରି ଜାରି ରଖନ୍ତୁ','Choose your language':'ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ','Choose your role':'ଆପଣଙ୍କ ଭୂମିକା ବାଛନ୍ତୁ','I’m a Farmer':'ମୁଁ ଜଣେ କୃଷକ','I’m a Visitor':'ମୁଁ ଜଣେ ପରିଦର୍ଶକ','Set up your farm':'ଆପଣଙ୍କ ଚାଷ ତଥ୍ୟ ସେଟ୍ କରନ୍ତୁ','Go to Dashboard':'ଡ୍ୟାଶବୋର୍ଡକୁ ଯାଆନ୍ତୁ','Welcome back':'ପୁଣିଥରେ ସ୍ୱାଗତ'
  },
  ur: {
    'Dashboard':'ڈیش بورڈ','Farm Intelligence':'زرعی ذہانت','Farm Health':'کھیت کی صحت','My Farm':'میرا کھیت','Farmer Memory':'کسان پروفائل','Daily Farm Plan':'روزانہ زرعی منصوبہ','Crop Lifecycle':'فصل کا دورِ حیات','Crop Health':'فصل کی صحت','Crop Recommendation':'فصل کی سفارش','Yield Prediction':'پیداوار کی پیش گوئی','Weather':'موسم','Market Intelligence':'بازار کی ذہانت','Smart Alerts':'اسمارٹ الرٹس','AI Assistant':'AI معاون','Government Schemes':'سرکاری اسکیمیں','Marketplace':'بازار','Notifications':'اطلاعات','Expense Tracker':'اخراجات ٹریکر','Analytics':'تجزیات','Farm Report':'کھیت کی رپورٹ','Season Report':'موسمی رپورٹ','Offline Mode':'آف لائن موڈ','Profile':'پروفائل','Settings':'ترتیبات','Sign in':'لاگ اِن کریں','Sign up':'سائن اَپ کریں','Login':'لاگ اِن','Logout':'لاگ آؤٹ','Save':'محفوظ کریں','Cancel':'منسوخ کریں','Continue':'جاری رکھیں','Back':'واپس','Search':'تلاش کریں','Loading…':'لوڈ ہو رہا ہے…','Loading...':'لوڈ ہو رہا ہے...','Error':'خرابی','Retry':'دوبارہ کوشش کریں','Close':'بند کریں','Edit':'ترمیم کریں','Delete':'حذف کریں','Add':'شامل کریں','Submit':'جمع کریں','Name':'نام','Email address':'ای میل پتہ','Password':'پاس ورڈ','Full name':'پورا نام','Location':'مقام','Farm size':'کھیت کا رقبہ','Soil type':'مٹی کی قسم','Irrigation method':'آبپاشی کا طریقہ','Current crop':'موجودہ فصل','Crop stage':'فصل کا مرحلہ','Save & Continue':'محفوظ کریں اور جاری رکھیں','Choose your language':'اپنی زبان منتخب کریں','Choose your role':'اپنا کردار منتخب کریں','I’m a Farmer':'میں کسان ہوں','I’m a Visitor':'میں مہمان ہوں','Set up your farm':'اپنا کھیت سیٹ کریں','Go to Dashboard':'ڈیش بورڈ پر جائیں','Welcome back':'خوش آمدید'
  }
};

// For the remaining scheduled languages, keep the catalog explicit and use the
// language's native label as a safe placeholder until feature copy is reviewed.
const REQUIRED_TRANSLATIONS: Record<string, Record<string, string>> = {
  as: {
    'Dashboard':'ডেশ্বব’ৰ্ড','Farm Intelligence':'কৃষি বুদ্ধিমত্তা','Farm Health':'খেতিৰ স্বাস্থ্য','My Farm':'মোৰ খেতি','Farmer Memory':'কৃষক প্ৰফাইল','Daily Farm Plan':'দৈনিক কৃষি পৰিকল্পনা','Crop Lifecycle':'শস্যৰ জীৱনচক্ৰ','Crop Health':'শস্যৰ স্বাস্থ্য','Crop Recommendation':'শস্যৰ পৰামৰ্শ','Yield Prediction':'উৎপাদন পূৰ্বানুমান','Weather':'বতৰ','Market Intelligence':'বজাৰ বুদ্ধিমত্তা','Smart Alerts':'স্মাৰ্ট সতৰ্কতা','AI Assistant':'AI সহায়ক','Government Schemes':'চৰকাৰী আঁচনি','Marketplace':'বজাৰ','Notifications':'জাননী','Expense Tracker':'খৰচ ট্ৰেকাৰ','Analytics':'বিশ্লেষণ','Farm Report':'খেতিৰ প্ৰতিবেদন','Season Report':'ঋতুৰ প্ৰতিবেদন','Offline Mode':'অফলাইন মোড','Profile':'প্ৰফাইল','Settings':'ছেটিংছ','Sign in':'ছাইন ইন','Sign up':'ছাইন আপ','Login':'লগ ইন','Logout':'লগ আউট','Save':'সংৰক্ষণ কৰক','Cancel':'বাতিল কৰক','Continue':'আগবাঢ়ক','Back':'পিছলৈ','Search':'সন্ধান কৰক','Loading…':'লোড হৈ আছে…','Loading...':'লোড হৈ আছে...','Error':'ত্ৰুটি','Retry':'পুনৰ চেষ্টা কৰক','Close':'বন্ধ কৰক','Edit':'সম্পাদনা কৰক','Delete':'মচক','Add':'যোগ কৰক','Submit':'দাখিল কৰক','Name':'নাম','Email address':'ইমেইল ঠিকনা','Password':'পাছৱৰ্ড','Full name':'সম্পূৰ্ণ নাম','Location':'স্থান','Farm size':'খেতিৰ আকাৰ','Soil type':'মাটিৰ প্ৰকাৰ','Irrigation method':'জলসিঞ্চন পদ্ধতি','Current crop':'বৰ্তমানৰ শস্য','Crop stage':'শস্যৰ পৰ্যায়','Save & Continue':'সংৰক্ষণ কৰি আগবাঢ়ক','Choose your language':'আপোনাৰ ভাষা বাছনি কৰক','Choose your role':'আপোনাৰ ভূমিকা বাছনি কৰক','I’m a Farmer':'মই এজন কৃষক','I’m a Visitor':'মই এজন দৰ্শনাৰ্থী','Set up your farm':'আপোনাৰ খেতি ছেট আপ কৰক','Go to Dashboard':'ডেশ্বব’ৰ্ডলৈ যাওক','Welcome back':'পুনৰ স্বাগতম'
  },
  bodo: {
    'Dashboard':'ड्यासबोर्ड','Farm Intelligence':'फार्म बुद्धिमत्ता','Farm Health':'फार्म सेहत','My Farm':'आंनि फार्म','Farmer Memory':'किसान प्रोफाइल','Daily Farm Plan':'सावारि फार्म योजना','Crop Lifecycle':'फसल जीवनचक्र','Crop Health':'फसल सेहत','Crop Recommendation':'फसल सिफारिश','Yield Prediction':'फसल उत्पादन अनुमान','Weather':'मौसम','Market Intelligence':'बाजार बुद्धिमत्ता','Smart Alerts':'स्मार्ट सावधानी','AI Assistant':'AI सहायक','Government Schemes':'सरकारी योजना','Marketplace':'बाजार','Notifications':'सूचना','Expense Tracker':'खर्च ट्रैकर','Analytics':'विश्लेषण','Farm Report':'फार्म रिपोर्ट','Season Report':'मौसम रिपोर्ट','Offline Mode':'ऑफलाइन मोड','Profile':'प्रोफाइल','Settings':'सेटिंग्स','Sign in':'साइन इन','Sign up':'साइन अप','Login':'लॉग इन','Logout':'लॉग आउट','Save':'सेभ','Cancel':'बातिल','Continue':'जारी राखो','Back':'उनाव','Search':'नागिर','Loading…':'लोड जाबो…','Loading...':'लोड जाबो...','Error':'गोरोनथि','Retry':'फिन नाजा','Close':'बन्द','Edit':'संपादन','Delete':'दोनथुम','Add':'जोड़','Submit':'दाखिल','Name':'मुं','Email address':'इमेल ठिकाना','Password':'पासवर्ड','Full name':'आबुं मुं','Location':'जायगा','Farm size':'फार्म साइज','Soil type':'माटि प्रकार','Irrigation method':'सिंचाइ पद्धति','Current crop':'दानि फसल','Crop stage':'फसल थाखि','Save & Continue':'सेभ खालामनानै जारी राखो','Choose your language':'नोंथांनि रावखौ सायख','Choose your role':'नोंथांनि भूमिका सायख','I’m a Farmer':'आं किसान','I’m a Visitor':'आं जाबायसारि','Set up your farm':'नोंथांनि फार्म साजाय','Go to Dashboard':'ड्यासबोर्डाव थां','Welcome back':'फिन स्वागतम'
  },
  dogri: {
    'Dashboard':'ਡੈਸ਼ਬੋਰਡ','Farm Intelligence':'ਖੇਤੀ ਬੁੱਧੀਮਤਾ','Farm Health':'ਖੇਤ ਸਿਹਤ','My Farm':'ਮੇਰਾ ਖੇਤ','Farmer Memory':'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ','Daily Farm Plan':'ਰੋਜ਼ਾਨਾ ਖੇਤੀ ਯੋਜਨਾ','Crop Lifecycle':'ਫਸਲ ਜੀਵਨ ਚੱਕਰ','Crop Health':'ਫਸਲ ਸਿਹਤ','Crop Recommendation':'ਫਸਲ ਸਿਫਾਰਸ਼','Yield Prediction':'ਉਪਜ ਅਨੁਮਾਨ','Weather':'ਮੌਸਮ','Market Intelligence':'ਮੰਡੀ ਬੁੱਧੀਮਤਾ','Smart Alerts':'ਸਮਾਰਟ ਚੇਤਾਵਨੀਆਂ','AI Assistant':'AI ਸਹਾਇਕ','Government Schemes':'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ','Marketplace':'ਬਾਜ਼ਾਰ','Notifications':'ਸੂਚਨਾਵਾਂ','Expense Tracker':'ਖਰਚ ਟ੍ਰੈਕਰ','Analytics':'ਵਿਸ਼ਲੇਸ਼ਣ','Farm Report':'ਖੇਤ ਰਿਪੋਰਟ','Season Report':'ਮੌਸਮ ਰਿਪੋਰਟ','Offline Mode':'ਆਫਲਾਈਨ ਮੋਡ','Profile':'ਪ੍ਰੋਫਾਈਲ','Settings':'ਸੈਟਿੰਗਾਂ','Sign in':'ਲੌਗ ਇਨ','Sign up':'ਸਾਈਨ ਅੱਪ','Login':'ਲੌਗ ਇਨ','Logout':'ਲੌਗ ਆਉਟ','Save':'ਸੰਭਾਲੋ','Cancel':'ਰੱਦ ਕਰੋ','Continue':'ਜਾਰੀ ਰੱਖੋ','Back':'ਪਿੱਛੇ','Search':'ਖੋਜੋ','Loading…':'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…','Loading...':'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...','Error':'ਗਲਤੀ','Retry':'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ','Close':'ਬੰਦ ਕਰੋ','Edit':'ਸੋਧੋ','Delete':'ਮਿਟਾਓ','Add':'ਜੋੜੋ','Submit':'ਜਮ੍ਹਾਂ ਕਰੋ','Name':'ਨਾਂ','Email address':'ਈਮੇਲ ਪਤਾ','Password':'ਪਾਸਵਰਡ','Full name':'ਪੂਰਾ ਨਾਂ','Location':'ਥਾਂ','Farm size':'ਖੇਤ ਦਾ ਆਕਾਰ','Soil type':'ਮਿੱਟੀ ਦੀ ਕਿਸਮ','Irrigation method':'ਸਿੰਚਾਈ ਵਿਧੀ','Current crop':'ਮੌਜੂਦਾ ਫਸਲ','Crop stage':'ਫਸਲ ਦੀ ਅਵਸਥਾ','Save & Continue':'ਸੰਭਾਲੋ ਤੇ ਜਾਰੀ ਰੱਖੋ','Choose your language':'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ','Choose your role':'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ','I’m a Farmer':'ਮੈਂ ਕਿਸਾਨ ਹਾਂ','I’m a Visitor':'ਮੈਂ ਮਹਿਮਾਨ ਹਾਂ','Set up your farm':'ਆਪਣਾ ਖੇਤ ਸੈੱਟ ਕਰੋ','Go to Dashboard':'ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ','Welcome back':'ਜੀ ਆਇਆਂ ਨੂੰ ਵਾਪਸ'
  },
  ks: {
    'Dashboard':'ڈیش بورڈ','Farm Intelligence':'زرعی ذہانت','Farm Health':'کھیت صحت','My Farm':'مےٚ کھیت','Farmer Memory':'کسان پروفائل','Daily Farm Plan':'روزانہ زرعی منصوبہ','Crop Lifecycle':'فصل چکر','Crop Health':'فصل صحت','Crop Recommendation':'فصل سفارش','Yield Prediction':'پیداوار پیش گوئی','Weather':'موسم','Market Intelligence':'بازار ذہانت','Smart Alerts':'سمارٹ انتباہات','AI Assistant':'AI معاون','Government Schemes':'سرکاری اسکیمیں','Marketplace':'بازار','Notifications':'اطلاعات','Expense Tracker':'اخراجات ٹریکر','Analytics':'تجزیہ','Farm Report':'کھیت رپورٹ','Season Report':'موسمی رپورٹ','Offline Mode':'آف لائن موڈ','Profile':'پروفائل','Settings':'ترتیبات','Sign in':'لاگ اِن','Sign up':'سائن اَپ','Login':'لاگ اِن','Logout':'لاگ آؤٹ','Save':'محفوظ','Cancel':'منسوخ','Continue':'جاری','Back':'واپس','Search':'تلاش','Loading…':'لوڈ ہو رہا ہے…','Loading...':'لوڈ ہو رہا ہے...','Error':'خرابی','Retry':'دوبارہ کوشش','Close':'بند','Edit':'ترمیم','Delete':'حذف','Add':'شامل','Submit':'جمع','Name':'نام','Email address':'ای میل پتہ','Password':'پاس ورڈ','Full name':'پورا نام','Location':'مقام','Farm size':'کھیت کا رقبہ','Soil type':'مٹی کی قسم','Irrigation method':'آبپاشی طریقہ','Current crop':'موجودہ فصل','Crop stage':'فصل مرحلہ','Save & Continue':'محفوظ کریں اور جاری رکھیں','Choose your language':'اپنی زبان منتخب کریں','Choose your role':'اپنا کردار منتخب کریں','I’m a Farmer':'میں کسان ہوں','I’m a Visitor':'میں مہمان ہوں','Set up your farm':'اپنا کھیت سیٹ کریں','Go to Dashboard':'ڈیش بورڈ پر جائیں','Welcome back':'خوش آمدید'
  },
  kok: {
    'Dashboard':'डॅशबोर्ड','Farm Intelligence':'शेती बुद्धीमत्ता','Farm Health':'शेताचें आरोग्य','My Farm':'म्हाजें शेत','Farmer Memory':'शेतकरी प्रोफायल','Daily Farm Plan':'दिसपट्टेचें शेती येवजण','Crop Lifecycle':'पिकाचें जीवनचक्र','Crop Health':'पिकाचें आरोग्य','Crop Recommendation':'पीक शिफारस','Yield Prediction':'उत्पादन अंदाज','Weather':'हवामान','Market Intelligence':'बाजार बुद्धीमत्ता','Smart Alerts':'स्मार्ट इशारे','AI Assistant':'AI सहाय्यक','Government Schemes':'सरकारी येवजणो','Marketplace':'बाजार','Notifications':'सुचोवणो','Expense Tracker':'खर्च ट्रॅकर','Analytics':'विश्लेषण','Farm Report':'शेत अहवाल','Season Report':'हंगाम अहवाल','Offline Mode':'ऑफलाइन मोड','Profile':'प्रोफायल','Settings':'सेटींग्स','Sign in':'साइन इन','Sign up':'साइन अप','Login':'लॉग इन','Logout':'लॉग आउट','Save':'जतन करात','Cancel':'रद्द करात','Continue':'फुडें वचात','Back':'फाटीं','Search':'सोदात','Loading…':'लोड जाता…','Loading...':'लोड जाता...','Error':'चूक','Retry':'परत प्रयत्न करात','Close':'बंद करात','Edit':'संपादित करात','Delete':'काडून उडोवात','Add':'जोडात','Submit':'सादर करात','Name':'नांव','Email address':'ईमेल पत्तो','Password':'पासवर्ड','Full name':'पुराय नांव','Location':'जागो','Farm size':'शेताचो आकार','Soil type':'मातीचो प्रकार','Irrigation method':'सिंचन पद्धत','Current crop':'सद्याचें पीक','Crop stage':'पिकाची अवस्था','Save & Continue':'जतन करून फुडें वचात','Choose your language':'तुमची भास निवडात','Choose your role':'तुमची भूमिका निवडात','I’m a Farmer':'हांव शेतकरी','I’m a Visitor':'हांव भेटकार','Set up your farm':'तुमचें शेत तयार करात','Go to Dashboard':'डॅशबोर्डाक वचात','Welcome back':'परत येवकार'
  },
  mai: {
    'Dashboard':'डैशबोर्ड','Farm Intelligence':'कृषि बुद्धिमत्ता','Farm Health':'खेत स्वास्थ्य','My Farm':'हमर खेत','Farmer Memory':'किसान प्रोफाइल','Daily Farm Plan':'दैनिक कृषि योजना','Crop Lifecycle':'फसल जीवनचक्र','Crop Health':'फसल स्वास्थ्य','Crop Recommendation':'फसल सिफारिश','Yield Prediction':'उपज अनुमान','Weather':'मौसम','Market Intelligence':'बाजार बुद्धिमत्ता','Smart Alerts':'स्मार्ट चेतावनी','AI Assistant':'AI सहायक','Government Schemes':'सरकारी योजना','Marketplace':'बाजार','Notifications':'सूचना','Expense Tracker':'खर्च ट्रैकर','Analytics':'विश्लेषण','Farm Report':'खेत रिपोर्ट','Season Report':'मौसम रिपोर्ट','Offline Mode':'ऑफलाइन मोड','Profile':'प्रोफाइल','Settings':'सेटिंग','Sign in':'साइन इन','Sign up':'साइन अप','Login':'लॉग इन','Logout':'लॉग आउट','Save':'सहेजू','Cancel':'रद्द करू','Continue':'आगाँ बढ़ू','Back':'पाछाँ','Search':'खोजू','Loading…':'लोड भऽ रहल अछि…','Loading...':'लोड भऽ रहल अछि...','Error':'त्रुटि','Retry':'फेर कोशिश करू','Close':'बन्द करू','Edit':'सम्पादन करू','Delete':'मेटाबू','Add':'जोड़ू','Submit':'जमा करू','Name':'नाम','Email address':'ईमेल पता','Password':'पासवर्ड','Full name':'पूरा नाम','Location':'स्थान','Farm size':'खेतक आकार','Soil type':'माटिक प्रकार','Irrigation method':'सिंचाई विधि','Current crop':'वर्तमान फसल','Crop stage':'फसल अवस्था','Save & Continue':'सहेजू आ आगाँ बढ़ू','Choose your language':'अपन भाषा चुनू','Choose your role':'अपन भूमिका चुनू','I’m a Farmer':'हम किसान छी','I’m a Visitor':'हम आगन्तुक छी','Set up your farm':'अपन खेत सेट करू','Go to Dashboard':'डैशबोर्ड पर जाउ','Welcome back':'फेर स्वागत अछि'
  },
  mni: {
    'Dashboard':'ꯗꯦꯁꯕꯣꯔꯗ','Farm Intelligence':'ꯐꯥꯔꯝ ꯏꯟꯇꯦꯂꯤꯖꯦꯟꯁ','Farm Health':'ꯐꯥꯔꯝ ꯍꯦꯂꯊ','My Farm':'ꯑꯩꯒꯤ ꯐꯥꯔꯝ','Farmer Memory':'ꯐꯥꯔꯃꯔ ꯄ꯭ꯔꯣꯐꯥꯏꯜ','Daily Farm Plan':'ꯅꯨꯃꯤꯠ ꯐꯥꯔꯝ ꯄ꯭ꯂꯥꯟ','Crop Lifecycle':'ꯀ꯭ꯔꯣꯞ ꯂꯥꯏꯐꯁꯥꯏꯀꯜ','Crop Health':'ꯀ꯭ꯔꯣꯞ ꯍꯦꯂꯊ','Crop Recommendation':'ꯀ꯭ꯔꯣꯞ ꯔꯤꯀꯃꯦꯟꯗꯦꯁꯟ','Yield Prediction':'ꯌꯤꯜꯗ ꯄ꯭ꯔꯤꯗꯤꯛꯁꯟ','Weather':'ꯋꯦꯗꯔ','Market Intelligence':'ꯃꯥꯔꯀꯦꯠ ꯏꯟꯇꯦꯂꯤꯖꯦꯟꯁ','Smart Alerts':'ꯁꯃꯥꯔꯠ ꯑꯂꯔꯠ','AI Assistant':'AI ꯑꯁꯤꯁꯇꯦꯟꯠ','Government Schemes':'ꯁꯔꯀꯥꯔꯒꯤ ꯁ꯭ꯀꯤꯝ','Marketplace':'ꯃꯥꯔꯀꯦꯠ','Notifications':'ꯅꯣꯇꯤꯐꯤꯀꯦꯁꯟ','Expense Tracker':'ꯏꯛꯁꯄꯦꯟꯁ ꯇ꯭ꯔꯥꯀꯔ','Analytics':'ꯑꯅꯥꯂꯤꯇꯤꯛꯁ','Farm Report':'ꯐꯥꯔꯝ ꯔꯤꯄꯣꯔꯠ','Season Report':'ꯁꯤꯖꯟ ꯔꯤꯄꯣꯔꯠ','Offline Mode':'ꯑꯣꯐꯂꯥꯏꯟ ꯃꯣꯗ','Profile':'ꯄ꯭ꯔꯣꯐꯥꯏꯜ','Settings':'ꯁꯦꯇꯤꯡꯁ','Sign in':'ꯁꯥꯏꯟ ꯏꯟ','Sign up':'ꯁꯥꯏꯟ ꯑꯞ','Login':'ꯂꯣꯒꯤꯟ','Logout':'ꯂꯣꯒꯑꯥꯎꯠ','Save':'ꯁꯦꯚ','Cancel':'ꯀꯦꯟꯁꯦꯜ','Continue':'ꯀꯟꯇꯤꯅ꯭ꯌꯨ','Back':'ꯕꯦꯛ','Search':'ꯁꯥꯔꯠꯁ','Loading…':'ꯂꯣꯗ ꯇꯧꯔꯤ…','Loading...':'ꯂꯣꯗ ꯇꯧꯔꯤ...','Error':'ꯑꯔꯥꯟ','Retry':'ꯑꯃꯨꯛ ꯇꯧ','Close':'ꯀꯂꯣꯁ','Edit':'ꯏꯗꯤꯠ','Delete':'ꯗꯤꯂꯤꯠ','Add':'ꯑꯦꯗ','Submit':'ꯁꯕꯃꯤꯠ','Name':'ꯃꯤꯡ','Email address':'ꯏꯃꯦꯜ ꯑꯗ꯭ꯔꯦꯁ','Password':'ꯄꯥꯁꯋꯥꯔꯗ','Full name':'ꯑꯄꯨꯟꯕ ꯃꯤꯡ','Location':'ꯂꯣꯀꯦꯁꯟ','Farm size':'ꯐꯥꯔꯝ ꯁꯥꯏꯖ','Soil type':'ꯁꯣꯏꯜ ꯇꯥꯏꯞ','Irrigation method':'ꯏꯔꯤꯒꯦꯁꯟ ꯃꯦꯊꯣꯗ','Current crop':'ꯍꯧꯖꯤꯀꯒꯤ ꯀ꯭ꯔꯣꯞ','Crop stage':'ꯀ꯭ꯔꯣꯞ ꯁ꯭ꯇꯦꯖ','Save & Continue':'ꯁꯦꯚ ꯇꯧꯕ ꯑꯃꯁꯨꯡ ꯀꯟꯇꯤꯅ꯭ꯌꯨ','Choose your language':'ꯅꯣꯡꯒꯤ ꯂꯣꯜ ꯈꯟꯕꯤꯌꯨ','Choose your role':'ꯅꯣꯡꯒꯤ ꯔꯣꯜ ꯈꯟꯕꯤꯌꯨ','I’m a Farmer':'ꯑꯩ ꯐꯥꯔꯃꯔꯅꯤ','I’m a Visitor':'ꯑꯩ ꯚꯤꯖꯤꯇꯔꯅꯤ','Set up your farm':'ꯅꯣꯡꯒꯤ ꯐꯥꯔꯝ ꯁꯦꯠ ꯇꯧ','Go to Dashboard':'ꯗꯦꯁꯕꯣꯔꯗꯗꯥ ꯆꯠꯂꯨ','Welcome back':'ꯑꯃꯨꯛ ꯍꯧꯖꯤꯛ ꯇꯥꯔꯤ'
  },
  ne: {
    'Dashboard':'ड्यासबोर्ड','Farm Intelligence':'कृषि बुद्धिमत्ता','Farm Health':'खेतको स्वास्थ्य','My Farm':'मेरो खेत','Farmer Memory':'किसान प्रोफाइल','Daily Farm Plan':'दैनिक कृषि योजना','Crop Lifecycle':'बाली जीवनचक्र','Crop Health':'बाली स्वास्थ्य','Crop Recommendation':'बाली सिफारिस','Yield Prediction':'उत्पादन पूर्वानुमान','Weather':'मौसम','Market Intelligence':'बजार बुद्धिमत्ता','Smart Alerts':'स्मार्ट सूचना','AI Assistant':'AI सहायक','Government Schemes':'सरकारी योजना','Marketplace':'बजार','Notifications':'सूचनाहरू','Expense Tracker':'खर्च ट्र्याकर','Analytics':'विश्लेषण','Farm Report':'खेत प्रतिवेदन','Season Report':'मौसम प्रतिवेदन','Offline Mode':'अफलाइन मोड','Profile':'प्रोफाइल','Settings':'सेटिङहरू','Sign in':'साइन इन','Sign up':'साइन अप','Login':'लग इन','Logout':'लग आउट','Save':'सुरक्षित गर्नुहोस्','Cancel':'रद्द गर्नुहोस्','Continue':'जारी राख्नुहोस्','Back':'पछाडि','Search':'खोज्नुहोस्','Loading…':'लोड हुँदैछ…','Loading...':'लोड हुँदैछ...','Error':'त्रुटि','Retry':'फेरि प्रयास गर्नुहोस्','Close':'बन्द गर्नुहोस्','Edit':'सम्पादन गर्नुहोस्','Delete':'मेटाउनुहोस्','Add':'थप्नुहोस्','Submit':'पेश गर्नुहोस्','Name':'नाम','Email address':'इमेल ठेगाना','Password':'पासवर्ड','Full name':'पूरा नाम','Location':'स्थान','Farm size':'खेतको आकार','Soil type':'माटोको प्रकार','Irrigation method':'सिँचाइ विधि','Current crop':'हालको बाली','Crop stage':'बालीको चरण','Save & Continue':'सुरक्षित गरेर जारी राख्नुहोस्','Choose your language':'आफ्नो भाषा छान्नुहोस्','Choose your role':'आफ्नो भूमिका छान्नुहोस्','I’m a Farmer':'म किसान हुँ','I’m a Visitor':'म आगन्तुक हुँ','Set up your farm':'आफ्नो खेत सेट अप गर्नुहोस्','Go to Dashboard':'ड्यासबोर्डमा जानुहोस्','Welcome back':'फेरि स्वागत छ'
  },
  sa: {
    'Dashboard':'फलकम्','Farm Intelligence':'कृषिबुद्धिः','Farm Health':'क्षेत्रस्वास्थ्यं','My Farm':'मम क्षेत्रम्','Farmer Memory':'कृषकप्रोफाइल','Daily Farm Plan':'दैनिककृषियोजना','Crop Lifecycle':'सस्यजीवनचक्रम्','Crop Health':'सस्यस्वास्थ्यं','Crop Recommendation':'सस्यपरामर्शः','Yield Prediction':'उत्पादनपूर्वानुमानम्','Weather':'वायुमानम्','Market Intelligence':'विपणिबुद्धिः','Smart Alerts':'स्मार्टसूचनाः','AI Assistant':'AI सहायकः','Government Schemes':'सर्वकारीययोजनाः','Marketplace':'विपणिः','Notifications':'सूचनाः','Expense Tracker':'व्ययअनुगामकः','Analytics':'विश्लेषणम्','Farm Report':'क्षेत्रप्रतिवेदनम्','Season Report':'ऋतुप्रतिवेदनम्','Offline Mode':'असञ्जालविधिः','Profile':'परिचयः','Settings':'व्यवस्थाः','Sign in':'प्रविशतु','Sign up':'खातं रचयतु','Login':'प्रवेशः','Logout':'निर्गमः','Save':'रक्षतु','Cancel':'निरस्यतु','Continue':'अनुवर्तयतु','Back':'पृष्ठतः','Search':'अन्विष्यतु','Loading…':'भार्यते…','Loading...':'भार्यते...','Error':'दोषः','Retry':'पुनः प्रयततु','Close':'पिधत्तु','Edit':'सम्पादयतु','Delete':'अपनयतु','Add':'योजयतु','Submit':'समर्पयतु','Name':'नाम','Email address':'ईमेल पता','Password':'गुप्तशब्दः','Full name':'पूर्णनाम','Location':'स्थानम्','Farm size':'क्षेत्रपरिमाणम्','Soil type':'मृत्तिकाप्रकारः','Irrigation method':'सिञ्चनविधिः','Current crop':'वर्तमानसस्यम्','Crop stage':'सस्यावस्था','Save & Continue':'रक्षित्वा अनुवर्तयतु','Choose your language':'स्वभाषां चिनुत','Choose your role':'स्वभूमिकां चिनुत','I’m a Farmer':'अहं कृषकः अस्मि','I’m a Visitor':'अहं अतिथिः अस्मि','Set up your farm':'स्वक्षेत्रं सज्जीकुरुत','Go to Dashboard':'फलकं गच्छतु','Welcome back':'पुनः स्वागतम्'
  },
  sat: {
    'Dashboard':'ᱰᱮᱥᱵᱚᱨᱰ','Farm Intelligence':'ᱪᱟᱥ ᱵᱩᱫᱷᱤᱢᱚᱛᱟ','Farm Health':'ᱪᱟᱥ ᱥᱮᱫᱟᱭ','My Farm':'ᱤᱧᱟᱹᱜ ᱪᱟᱥ','Farmer Memory':'ᱪᱟᱥᱤ ᱯᱨᱚᱯᱷᱟᱭᱞ','Daily Farm Plan':'ᱫᱤᱱᱟ ᱪᱟᱥ ᱯᱞᱟᱱ','Crop Lifecycle':'ᱯᱟᱦᱴᱟ ᱡᱤᱵᱚᱱᱪᱟᱠᱨᱚ','Crop Health':'ᱯᱟᱦᱴᱟ ᱥᱮᱫᱟᱭ','Crop Recommendation':'ᱯᱟᱦᱴᱟ ᱥᱟᱞᱟᱦ','Yield Prediction':'ᱩᱛᱯᱟᱫᱚᱱ ᱟᱫᱟᱹᱭ','Weather':'ᱢᱚᱦᱚᱨ','Market Intelligence':'ᱵᱟᱡᱟᱨ ᱵᱩᱫᱷᱤᱢᱚᱛᱟ','Smart Alerts':'ᱥᱢᱟᱨᱴ ᱥᱟᱵᱷᱟᱹᱱ','AI Assistant':'AI ᱥᱟᱦᱟᱭᱚᱜ','Government Schemes':'ᱥᱚᱨᱠᱟᱨ ᱥᱠᱤᱢ','Marketplace':'ᱵᱟᱡᱟᱨ','Notifications':'ᱥᱩᱪᱚᱱᱟ','Expense Tracker':'ᱠᱷᱚᱨᱚᱪ ᱴᱨᱮᱠᱟᱨ','Analytics':'ᱵᱤᱥᱞᱮᱥᱚᱱ','Farm Report':'ᱪᱟᱥ ᱨᱤᱯᱚᱨᱴ','Season Report':'ᱢᱚᱦᱟ ᱨᱤᱯᱚᱨᱴ','Offline Mode':'ᱚᱯᱷᱞᱟᱭᱤᱱ ᱢᱚᱰ','Profile':'ᱯᱨᱚᱯᱷᱟᱭᱞ','Settings':'ᱥᱮᱴᱤᱝᱥ','Sign in':'ᱥᱟᱭᱤᱱ ᱤᱱ','Sign up':'ᱥᱟᱭᱤᱱ ᱟᱯ','Login':'ᱞᱚᱜᱤᱱ','Logout':'ᱞᱚᱜᱟᱣᱩᱴ','Save':'ᱥᱟᱵᱷᱟᱣ','Cancel':'ᱵᱟᱛᱤᱞ','Continue':'ᱞᱟᱦᱟ','Back':'ᱦᱟᱹᱛᱤᱧ','Search':'ᱥᱮᱫᱟ','Loading…':'ᱞᱳᱰ ᱦᱚᱪᱚ…','Loading...':'ᱞᱳᱰ ᱦᱚᱪᱚ...','Error':'ᱵᱷᱩᱞ','Retry':'ᱫᱚᱦᱲᱟ ᱪᱮᱥᱴᱟ','Close':'ᱵᱚᱱᱫᱚ','Edit':'ᱥᱟᱢᱯᱟᱫᱚᱱ','Delete':'ᱢᱮᱴᱟᱣ','Add':'ᱡᱚᱲᱟᱣ','Submit':'ᱡᱚᱢᱟ','Name':'ᱧᱩᱛᱩᱢ','Email address':'ᱤᱢᱮᱞ ᱴᱷᱤᱠᱟᱱᱟ','Password':'ᱯᱟᱥᱣᱟᱨᱰ','Full name':'ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ','Location':'ᱴᱷᱟᱶ','Farm size':'ᱪᱟᱥ ᱢᱟᱯ','Soil type':'ᱦᱟᱥᱟ ᱞᱮᱠᱟ','Irrigation method':'ᱫᱟᱜ ᱥᱤᱧᱪᱟᱹᱭ','Current crop':'ᱱᱤᱛᱚᱜ ᱯᱟᱦᱴᱟ','Crop stage':'ᱯᱟᱦᱴᱟ ᱫᱟᱹᱭ','Save & Continue':'ᱥᱟᱵᱷᱟᱣ ᱠᱟᱛᱮ ᱞᱟᱦᱟ','Choose your language':'ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱱᱟᱣ','Choose your role':'ᱟᱢᱟᱜ ᱵᱷᱩᱢᱤᱠᱟ ᱵᱟᱪᱷᱱᱟᱣ','I’m a Farmer':'ᱤᱧ ᱪᱟᱥᱤ ᱠᱟᱱᱟ','I’m a Visitor':'ᱤᱧ ᱵᱷᱤᱡᱤᱴᱚᱨ ᱠᱟᱱᱟ','Set up your farm':'ᱟᱢᱟᱜ ᱪᱟᱥ ᱥᱮᱴ ᱠᱟᱢ','Go to Dashboard':'ᱰᱮᱥᱵᱚᱨᱰ ᱨᱮ ᱥᱮᱱᱚᱜ','Welcome back':'ᱫᱚᱦᱲᱟ ᱡᱚᱦᱟᱨ'
  },
  sd: {
    'Dashboard':'ڊيش بورڊ','Farm Intelligence':'زرعي ذهانت','Farm Health':'ٻني جي صحت','My Farm':'منهنجو کيت','Farmer Memory':'هاري پروفائل','Daily Farm Plan':'روزاني زرعي منصوبو','Crop Lifecycle':'فصل جو زندگي چڪر','Crop Health':'فصل جي صحت','Crop Recommendation':'فصل سفارش','Yield Prediction':'پيداوار اڳڪٿي','Weather':'موسم','Market Intelligence':'بازار ذهانت','Smart Alerts':'سمارٽ خبرداريون','AI Assistant':'AI مددگار','Government Schemes':'سرڪاري اسڪيمون','Marketplace':'بازار','Notifications':'اطلاعات','Expense Tracker':'خرچ ٽريڪر','Analytics':'تجزيو','Farm Report':'کيت رپورٽ','Season Report':'موسمي رپورٽ','Offline Mode':'آف لائن موڊ','Profile':'پروفائل','Settings':'سيٽنگون','Sign in':'سائن اِن','Sign up':'سائن اَپ','Login':'لاگ اِن','Logout':'لاگ آئوٽ','Save':'محفوظ ڪريو','Cancel':'رد ڪريو','Continue':'جاري رکو','Back':'واپس','Search':'ڳوليو','Loading…':'لوڊ ٿي رهيو آهي…','Loading...':'لوڊ ٿي رهيو آهي...','Error':'غلطي','Retry':'ٻيهر ڪوشش ڪريو','Close':'بند ڪريو','Edit':'ترميم ڪريو','Delete':'ختم ڪريو','Add':'شامل ڪريو','Submit':'جمع ڪريو','Name':'نالو','Email address':'اي ميل پتو','Password':'پاسورڊ','Full name':'پورو نالو','Location':'جڳهه','Farm size':'کيت جو ماپو','Soil type':'مٽي جو قسم','Irrigation method':'آبپاشي جو طريقو','Current crop':'موجوده فصل','Crop stage':'فصل جو مرحلو','Save & Continue':'محفوظ ڪري جاري رکو','Choose your language':'پنهنجي ٻولي چونڊيو','Choose your role':'پنهنجو ڪردار چونڊيو','I’m a Farmer':'مان هاري آهيان','I’m a Visitor':'مان مهمان آهيان','Set up your farm':'پنهنجو کيت سيٽ ڪريو','Go to Dashboard':'ڊيش بورڊ تي وڃو','Welcome back':'ڀليڪار واپس'
  }
};

for (const [code, entries] of Object.entries(REQUIRED_TRANSLATIONS)) {
  UI_TRANSLATIONS[code] = { ...(UI_TRANSLATIONS[code] ?? {}), ...entries };
}

export function translateUiText(text: string, language: string): string {
  return UI_TRANSLATIONS[language]?.[text] ?? text;
}
