import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArrowRight, Brain, CheckCircle2, CloudRain, Database, IndianRupee, Leaf, Loader2, RefreshCw, Sparkles, Sprout, Target, TrendingDown, TrendingUp } from 'lucide-react';
import { useDashboard } from '@/hooks/useDashboard';
import { useAuth } from '@/context/AuthContext';
import { buildCopilotContext } from '@/services/aiCopilotService';
import { buildFarmActions, type FarmAction } from '@/services/farmDecisionService';

function money(value:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number.isFinite(value)?value:0)}
function pct(value:number){return Math.max(0,Math.min(100,Number.isFinite(value)?value:0))}
const tone:{[key:string]:string}={high:'border-red-200 bg-red-50 text-red-800',medium:'border-amber-200 bg-amber-50 text-amber-800',low:'border-sky-200 bg-sky-50 text-sky-800'};
const sourceIcon:{[key:string]:React.ElementType}={weather:CloudRain,crop:Sprout,market:TrendingUp,finance:IndianRupee,profile:Target};

export default function FarmIntelligencePage(){
 const {user}=useAuth(); const {data,loading,error,refetch}=useDashboard();
 const [actions,setActions]=useState<FarmAction[]>([]); const [decisionLoading,setDecisionLoading]=useState(false); const [decisionError,setDecisionError]=useState('');
 const loadDecisions=useCallback(async()=>{if(!user?.id)return;setDecisionLoading(true);setDecisionError('');try{const context=await buildCopilotContext(user.id);setActions(buildFarmActions(context));}catch(e){setDecisionError(e instanceof Error?e.message:'Unable to load decision signals.');setActions([])}finally{setDecisionLoading(false)}},[user?.id]);
 useEffect(()=>{void loadDecisions()},[loadDecisions]);
 const topCrop=data?.cropStatus?.[0]; const health=pct(data?.kpis.avgHealth??0); const revenue=data?.finance.expectedRevenue??0; const profit=data?.finance.expectedProfit??0; const expenses=data?.finance.totalExpenses??0; const ratio=revenue>0?Math.round(expenses/revenue*100):null;
 return <div className="space-y-6">
  <section className="relative overflow-hidden rounded-3xl border border-emerald-100 bg-gradient-to-r from-white via-emerald-50 to-emerald-100 shadow-card"><div className="absolute inset-0 bg-gradient-to-r from-white via-white/90 to-transparent"/><div className="relative px-5 py-8 sm:px-8 sm:py-10"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/80 px-3 py-1 text-xs font-semibold text-emerald-700"><Brain className="h-4 w-4"/>Decision intelligence</div><h1 className="text-3xl font-bold text-emerald-950 sm:text-4xl">Farm Intelligence</h1><p className="mt-2 max-w-2xl text-base leading-7 text-slate-700">Turn your real farm records, crop status, weather, tasks and financial data into prioritized farm decisions.</p></div></section>
  <section className="rounded-2xl border bg-white p-4 shadow-soft sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-600">Farm context</p><h2 className="mt-1 text-lg font-semibold text-slate-900">{data?.farmerProfile.name??'Your farm'}</h2><p className="text-sm text-slate-500">{data?.farmerProfile.location??'Location not recorded'} · {data?.kpis.totalAcreage??0} acres · {data?.kpis.activeFields??0} active fields</p></div><div className="flex flex-wrap gap-2">{topCrop&&<span className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2 text-sm font-medium text-emerald-800"><Leaf className="h-4 w-4"/>{topCrop.name} · {topCrop.stage}</span>}<button onClick={()=>{void refetch();void loadDecisions()}} disabled={loading||decisionLoading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading||decisionLoading?'animate-spin':''}`}/>Refresh intelligence</button></div></div></section>
  {(loading||decisionLoading)&&<div className="flex items-center justify-center rounded-2xl border bg-white py-12 text-sm text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Analyzing current farm records…</div>}
  {!loading&&error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0"/><div><p className="font-semibold">Farm intelligence is temporarily unavailable.</p><p className="mt-1">{error}</p></div></div></div>}
  {!decisionLoading&&decisionError&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Decision engine could not load: {decisionError}</div>}
  {!loading&&!error&&data&&<>
   <section className="rounded-3xl border border-emerald-100 bg-gradient-to-br from-emerald-50 to-white p-5 shadow-soft sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 text-xs font-semibold text-emerald-700 shadow-sm"><Sparkles className="h-4 w-4"/>Intelligence engine</div><h2 className="mt-3 text-2xl font-bold text-slate-900">Recommended decisions</h2><p className="mt-1 text-sm text-slate-600">Prioritized directly from the shared Farm Intelligence decision engine.</p></div><div className="rounded-2xl bg-white px-4 py-3 text-right shadow-sm"><p className="text-xs text-slate-500">Recorded farm health</p><p className="text-2xl font-bold text-emerald-700">{health}%</p></div></div>{actions.length?<div className="mt-5 grid gap-4 lg:grid-cols-2">{actions.map((a,i)=>{const Icon=sourceIcon[a.source]??Brain;return <article key={a.id} className={`rounded-2xl border p-5 ${tone[a.priority]??tone.low}`}><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white"><Icon className="h-5 w-5"/></div><div className="min-w-0"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider"><span>Decision {i+1}</span><CheckCircle2 className="h-4 w-4"/></div><h3 className="mt-1 font-semibold">{a.title}</h3><p className="mt-1 text-sm leading-6 opacity-90">{a.detail}</p><div className="mt-3 flex items-center gap-2 text-xs font-semibold">Priority: {a.priority}<ArrowRight className="h-3.5 w-3.5"/></div></div></div></article>})}</div>:<div className="mt-5 rounded-2xl border border-dashed bg-white p-6 text-center text-sm text-slate-500">No decision signals are available yet. Add farm, field or crop records to build context.</div>}</section>
   <section className="grid gap-4 lg:grid-cols-5"><article className="lg:col-span-3 rounded-2xl border bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-600">Field intelligence</p><h2 className="mt-1 text-xl font-bold text-slate-900">Field-by-field signals</h2></div><Sprout className="h-5 w-5 text-emerald-600"/></div>{data.fields?.length?<div className="mt-4 space-y-3">{data.fields.slice(0,6).map(f=><div key={f.name} className="rounded-xl border bg-slate-50/70 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{f.name}</p><p className="text-xs text-slate-500">{f.crop} · {f.stage} · {f.area}</p></div><div className="min-w-32"><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Health</span><span>{f.health}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-emerald-500" style={{width:`${pct(f.health)}%`}}/></div></div></div></div>)}</div>:<div className="mt-4 rounded-xl border border-dashed p-5 text-sm text-slate-500">No field records are available yet.</div>}</article>
   <article className="lg:col-span-2 rounded-2xl border bg-white p-5 shadow-soft"><div className="flex items-center gap-2"><IndianRupee className="h-5 w-5 text-amber-600"/><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-600">Financial signal</p><h2 className="mt-1 text-xl font-bold text-slate-900">Farm economics</h2></div></div><div className="mt-5 space-y-4"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Recorded expenses</p><p className="mt-1 text-2xl font-bold text-slate-900">{money(expenses)}</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border p-4"><p className="text-xs text-slate-500">Expected revenue</p><p className="mt-1 font-bold">{money(revenue)}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-slate-500">Expected profit</p><p className={`mt-1 font-bold ${profit>=0?'text-emerald-700':'text-rose-700'}`}>{money(profit)}</p></div></div><div className="rounded-xl border border-amber-100 bg-amber-50/60 p-4 text-sm text-amber-900">{profit>=0?<TrendingUp className="mr-2 inline h-4 w-4"/>:<TrendingDown className="mr-2 inline h-4 w-4"/>}{ratio===null?'Revenue data not yet recorded':`${ratio}% of recorded revenue is covered by expenses`}</div></div></article></section>
   <section className="rounded-2xl border bg-slate-950 p-5 text-white shadow-soft sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-emerald-300"><Database className="h-5 w-5"/><span className="text-sm font-semibold">Intelligence provenance</span></div><h2 className="mt-2 text-xl font-bold">Real records, shared decision logic</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-300">Recommendations use the authenticated farmer context, weather, crops, verified market records and expenses available to the decision engine.</p></div><div className="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-slate-300">No sample values are generated for missing farm records.</div></div></section>
  </>}
 </div>;
}
