import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { addMarketplaceListing, createMarketplaceOrder, cancelMarketplaceOrder, getMarketplaceListings, getMyMarketplaceOrders, removeMarketplaceListing, updateMarketplaceOrderStatus, type MarketplaceCategory, type MarketplaceListing, type MarketplaceOrder } from '@/services/marketplaceService';
import GlassCard from '@/components/ui/GlassCard';
import { Package, Plus, Search, MapPin, ShoppingCart, Tractor, X, Trash2, Wheat, Sprout, Apple, Boxes, Wrench, ClipboardList, Check, Ban, Droplets, FlaskConical, Bug } from 'lucide-react';

const filters = [
  { key: 'All', label: 'All Products', icon: Boxes }, { key: 'Crops', label: 'Crops', icon: Wheat }, { key: 'Seeds', label: 'Seeds', icon: Sprout },
  { key: 'Fertilizers', label: 'Fertilizers', icon: FlaskConical }, { key: 'Pesticides', label: 'Pesticides & Bio Inputs', icon: Bug },
  { key: 'Equipment', label: 'Farm Equipment', icon: Tractor }, { key: 'Irrigation', label: 'Irrigation & Tools', icon: Droplets }, { key: 'Vegetables', label: 'Vegetables', icon: Sprout }, { key: 'Fruits', label: 'Fruits', icon: Apple },
] as const;
type ProductFilter = typeof filters[number]['key'];
const inputClass = 'w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-ink-900 outline-none transition focus:border-brand-400 focus:ring-2 focus:ring-brand-100';
const words: Record<Exclude<ProductFilter, 'All'>, string[]> = {
  Crops: ['crop','paddy','rice','wheat','maize','cotton','sugarcane','millet','groundnut','turmeric'], Seeds: ['seed','seedling','sapling'],
  Fertilizers: ['fertilizer','urea','dap','npk','potash','mop','compost','vermicompost','manure','micronutrient'], Pesticides: ['pesticide','insecticide','fungicide','herbicide','bio input','biopesticide','neem','trichoderma'],
  Equipment: ['tractor','sprayer','harvester','cultivator','equipment','machine','power tiller'], Irrigation: ['irrigation','drip','sprinkler','pipe','hose','shovel','hoe','tool','plough','water pump'],
  Vegetables: ['vegetable','tomato','onion','brinjal','chilli','okra','cabbage','carrot'], Fruits: ['fruit','mango','banana','papaya','guava','orange','grape'],
};
const productCatalog: Array<{ name: string; category: ProductFilter; description: string; unit: string }> = [
  { name: 'Urea 45 kg', category: 'Fertilizers', description: 'Nitrogen fertilizer for crop nutrition', unit: 'bag' },
  { name: 'DAP 50 kg', category: 'Fertilizers', description: 'Phosphorus and nitrogen fertilizer', unit: 'bag' },
  { name: 'NPK 10:26:26', category: 'Fertilizers', description: 'Balanced NPK fertilizer for field crops', unit: 'bag' },
  { name: 'NPK 19:19:19', category: 'Fertilizers', description: 'Water-soluble balanced fertilizer', unit: 'bag' },
  { name: 'MOP / Potash', category: 'Fertilizers', description: 'Potassium fertilizer for crop nutrition', unit: 'bag' },
  { name: 'Vermicompost', category: 'Fertilizers', description: 'Organic soil amendment', unit: 'kg' },
  { name: 'Micronutrient Mixture', category: 'Fertilizers', description: 'Micronutrient input for crop nutrition', unit: 'kg' },
  { name: 'Paddy Seeds', category: 'Seeds', description: 'Rice seed varieties for cultivation', unit: 'kg' },
  { name: 'Maize Seeds', category: 'Seeds', description: 'Hybrid and open-pollinated maize seed', unit: 'kg' },
  { name: 'Groundnut Seeds', category: 'Seeds', description: 'Groundnut seed for field planting', unit: 'kg' },
  { name: 'Cotton Seeds', category: 'Seeds', description: 'Cotton seed for commercial cultivation', unit: 'packet' },
  { name: 'Tomato Seeds', category: 'Seeds', description: 'Tomato seed for vegetable cultivation', unit: 'packet' },
  { name: 'Chilli Seeds', category: 'Seeds', description: 'Chilli seed for vegetable cultivation', unit: 'packet' },
  { name: 'Neem Bio-pesticide', category: 'Pesticides', description: 'Neem-based crop protection input', unit: 'litre' },
  { name: 'Trichoderma Bio-fungicide', category: 'Pesticides', description: 'Biological crop protection input', unit: 'kg' },
  { name: 'Bio-fungicide', category: 'Pesticides', description: 'Biological fungal disease management input', unit: 'litre' },
  { name: 'Crop Insecticide', category: 'Pesticides', description: 'Crop protection insect control product', unit: 'litre' },
  { name: 'Drip Irrigation Kit', category: 'Irrigation', description: 'Drip irrigation components for farms', unit: 'set' },
  { name: 'Farm Sprayer', category: 'Irrigation', description: 'Hand or power-operated crop sprayer', unit: 'piece' },
  { name: 'Water Pump', category: 'Irrigation', description: 'Farm water pumping equipment', unit: 'piece' },
  { name: 'Power Tiller', category: 'Equipment', description: 'Compact farm tillage equipment', unit: 'piece' },
  { name: 'Tractor Cultivator', category: 'Equipment', description: 'Tillage implement for tractor use', unit: 'piece' },
  { name: 'Seed Drill', category: 'Equipment', description: 'Equipment for accurate seed placement', unit: 'piece' },
  { name: 'Paddy', category: 'Crops', description: 'Farm-produced paddy for buyers', unit: 'quintal' },
  { name: 'Maize', category: 'Crops', description: 'Farm-produced maize for buyers', unit: 'quintal' },
  { name: 'Groundnut', category: 'Crops', description: 'Farm-produced groundnut for buyers', unit: 'quintal' },
  { name: 'Turmeric', category: 'Crops', description: 'Farm-produced turmeric', unit: 'quintal' },
  { name: 'Tomato', category: 'Vegetables', description: 'Fresh farm-produced tomatoes', unit: 'kg' },
  { name: 'Onion', category: 'Vegetables', description: 'Fresh farm-produced onions', unit: 'kg' },
  { name: 'Chilli', category: 'Vegetables', description: 'Fresh farm-produced chilli', unit: 'kg' },
  { name: 'Banana', category: 'Fruits', description: 'Fresh farm-produced banana', unit: 'kg' },
  { name: 'Mango', category: 'Fruits', description: 'Fresh farm-produced mango', unit: 'kg' },
];
function matches(item: MarketplaceListing, filter: ProductFilter) {
  if (filter === 'All') return true;
  const text = `${item.productName} ${item.description}`.toLowerCase();
  if (filter === 'Crops') return item.category === 'Crops' || words.Crops.some(w => text.includes(w));
  if (filter === 'Seeds') return item.category === 'Seeds' || words.Seeds.some(w => text.includes(w));
  if (filter === 'Vegetables') return item.category === 'Vegetables' || words.Vegetables.some(w => text.includes(w));
  if (filter === 'Fruits') return item.category === 'Fruits' || words.Fruits.some(w => text.includes(w));
  if (filter === 'Fertilizers') return item.category === 'Inputs' && words.Fertilizers.some(w => text.includes(w));
  if (filter === 'Pesticides') return item.category === 'Inputs' && words.Pesticides.some(w => text.includes(w));
  if (filter === 'Equipment') return item.category === 'Equipment' && !words.Irrigation.some(w => text.includes(w));
  return item.category === 'Equipment' && words.Irrigation.some(w => text.includes(w));
}
function label(item: MarketplaceListing) {
  const text = `${item.productName} ${item.description}`.toLowerCase();
  if (item.category === 'Inputs') return words.Fertilizers.some(w => text.includes(w)) ? 'Fertilizer / Crop Input' : words.Pesticides.some(w => text.includes(w)) ? 'Pesticide / Bio Input' : 'Crop Input';
  if (item.category === 'Equipment') return words.Irrigation.some(w => text.includes(w)) ? 'Irrigation / Tool' : 'Farm Equipment';
  return item.category;
}
function catalogMatches(item: typeof productCatalog[number], filter: ProductFilter, query: string) {
  const text = `${item.name} ${item.description}`.toLowerCase();
  return (filter === 'All' || item.category === filter) && (!query || text.includes(query));
}

export default function ProductMarketplacePage() {
  const { user } = useAuth(); const { language } = useI18n();
  const [listings, setListings] = useState<MarketplaceListing[]>([]); const [orders, setOrders] = useState<MarketplaceOrder[]>([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<ProductFilter>('All');
  const [showSell, setShowSell] = useState(false); const [selected, setSelected] = useState<MarketplaceListing | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({ productName: '', category: 'Inputs' as MarketplaceCategory, quantity: '', unit: 'bag', price: '', location: '', description: '' }); const [orderQty, setOrderQty] = useState(''); const [orderNote, setOrderNote] = useState('');
  const isFarmer = user?.user_metadata?.role === 'farmer';
  const refresh = useCallback(async () => { setLoading(true); setError(''); try { const [l, o] = await Promise.all([getMarketplaceListings(), user ? getMyMarketplaceOrders(user.id) : Promise.resolve([])]); setListings(l); setOrders(o); } catch (e) { setError(e instanceof Error ? e.message : 'Marketplace data could not be loaded.'); } finally { setLoading(false); } }, [user]);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 60000); return () => window.clearInterval(timer); }, [refresh]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return listings.filter(item => { const text = `${item.productName} ${item.sellerName} ${item.location} ${item.description}`.toLowerCase(); return matches(item, filter) && (!q || text.includes(q)); }); }, [listings, query, filter]);
  const catalog = useMemo(() => { const q = query.trim().toLowerCase(); return productCatalog.filter(item => catalogMatches(item, filter, q)); }, [query, filter]);
  const currency = (n: number) => `₹${n.toLocaleString('en-IN')}`; const dateLabel = (s: string) => new Intl.DateTimeFormat(language === 'en' ? 'en-IN' : `${language}-IN`, { day: 'numeric', month: 'short' }).format(new Date(s));
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!user || !isFarmer) return; const quantity = Number(form.quantity), price = Number(form.price); if (!form.productName.trim() || quantity <= 0 || !Number.isFinite(quantity) || price < 0 || !Number.isFinite(price) || !form.location.trim()) { setError('Enter a valid product, quantity, price and location.'); return; } try { await addMarketplaceListing({ sellerId: user.id, productName: form.productName.trim(), category: form.category, quantity, unit: form.unit, price, location: form.location.trim(), description: form.description.trim() || 'Agricultural product available for buyers.', sellerName: user.user_metadata?.name || user.email?.split('@')[0] || 'Farmer' }); setShowSell(false); setForm({ productName: '', category: 'Inputs', quantity: '', unit: 'bag', price: '', location: '', description: '' }); setMessage('Product listed successfully.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not publish the product.'); } };
  const order = async (e: React.FormEvent) => { e.preventDefault(); if (!user) { setError('Please sign in to place an order.'); return; } if (!selected) return; const quantity = Number(orderQty); if (!Number.isFinite(quantity) || quantity <= 0 || quantity > selected.availableQuantity) { setError(`Enter a quantity between 0 and ${selected.availableQuantity} ${selected.unit}.`); return; } try { await createMarketplaceOrder({ listingId: selected.id, buyerId: user.id, quantity, buyerNote: orderNote.trim() || undefined }); setSelected(null); setOrderQty(''); setOrderNote(''); setMessage('Order request placed.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not place the order.'); } };
  const cancel = async (o: MarketplaceOrder) => { if (!user) return; try { await cancelMarketplaceOrder(o.id, user.id); setMessage('Order cancelled.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not cancel the order.'); } };
  const update = async (o: MarketplaceOrder, status: 'accepted' | 'rejected' | 'completed') => { if (!user) return; try { await updateMarketplaceOrderStatus({ orderId: o.id, userId: user.id, status }); setMessage(`Order marked ${status}.`); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update the order.'); } };
  return <div className="space-y-5">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-brand-700"><ShoppingCart size={20}/><span className="text-sm font-bold">Puthumai Uzhavan</span></div><h1 className="mt-1 font-display text-3xl font-extrabold text-ink-900">Agricultural Product Marketplace</h1><p className="mt-1 max-w-3xl text-sm leading-6 text-ink-600">Buy and sell seeds, fertilizers, pesticides, bio-inputs, irrigation products, farm tools, equipment and farm produce.</p></div>{isFarmer && <button onClick={() => setShowSell(true)} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-brand-600 px-5 py-3 font-bold text-white shadow-card hover:bg-brand-700"><Plus size={18}/> Sell / List Product</button>}</div>
    {message && <Notice text={message} close={() => setMessage('')}/>} {error && <Notice text={error} error close={() => setError('')}/>} 
    <GlassCard padding="lg"><div className="flex flex-col gap-4"><label className="relative"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-ink-400"/><input value={query} onChange={e => setQuery(e.target.value)} className={`${inputClass} pl-11`} placeholder="Search fertilizer, urea, NPK, seeds, pesticide, tractor, drip, tools..."/></label><div className="flex gap-2 overflow-x-auto scrollbar-none">{filters.map(({key,label: text,icon:Icon}) => <button key={key} onClick={() => setFilter(key)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${filter === key ? 'bg-brand-600 text-white' : 'bg-gray-100 text-ink-700 hover:bg-brand-50'}`}><Icon size={15}/>{text}</button>)}</div></div></GlassCard>
    {!loading && <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Tile icon={FlaskConical} title="Fertilizers" text="Urea, DAP, NPK & organic inputs" onClick={() => setFilter('Fertilizers')}/><Tile icon={Bug} title="Crop Protection" text="Pesticides & bio-inputs" onClick={() => setFilter('Pesticides')}/><Tile icon={Sprout} title="Seeds" text="Crop seeds & planting material" onClick={() => setFilter('Seeds')}/><Tile icon={Wrench} title="Farm Tools" text="Equipment, irrigation & tools" onClick={() => setFilter('Equipment')}/></div>}
    {loading ? <GlassCard padding="lg"><p className="py-10 text-center text-sm text-ink-500">Loading agricultural products…</p></GlassCard> : filtered.length ? <><div className="flex items-center justify-between"><h2 className="font-display text-xl font-extrabold text-ink-900">Live seller listings</h2><span className="text-xs font-semibold text-ink-500">{filtered.length} listing{filtered.length === 1 ? '' : 's'}</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item => <ProductCard key={item.id} item={item} own={item.sellerId === user?.id} buy={() => { setSelected(item); setOrderQty(''); }} remove={async () => { try { await removeMarketplaceListing(item.id, user!.id); setMessage('Product listing removed.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove product.'); } }} currency={currency} dateLabel={dateLabel}/>)}</div></> : <><div className="flex items-center justify-between"><div><h2 className="font-display text-xl font-extrabold text-ink-900">Agricultural Product Catalog</h2><p className="mt-1 text-sm text-ink-500">Common products available through farmer and seller listings.</p></div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700">{catalog.length} products</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{catalog.map(item => <CatalogCard key={`${item.category}-${item.name}`} item={item}/>)}</div><GlassCard padding="lg"><div className="flex flex-col items-center justify-between gap-4 text-center sm:flex-row sm:text-left"><div><h3 className="font-display text-lg font-extrabold text-ink-900">Want to buy a catalog product?</h3><p className="mt-1 text-sm text-ink-500">Use Sell / List Product to publish a real seller listing with price, stock and location. Buy / Order appears only on live listings.</p></div>{isFarmer && <button onClick={() => setShowSell(true)} className="shrink-0 rounded-2xl bg-brand-600 px-5 py-3 text-sm font-bold text-white">List a Product</button>}</div></GlassCard></>}
    {user && <GlassCard padding="lg"><div className="flex items-center gap-2"><ClipboardList size={20} className="text-brand-600"/><h2 className="font-display text-xl font-extrabold text-ink-900">My marketplace orders</h2></div>{orders.length ? <div className="mt-4 space-y-3">{orders.map(o => <OrderRow key={o.id} order={o} userId={user.id} update={update} cancel={cancel} dateLabel={dateLabel} currency={currency}/>)}</div> : <p className="mt-3 text-sm text-ink-500">No marketplace orders yet.</p>}</GlassCard>}
    {showSell && <Modal title="Sell / List an Agricultural Product" close={() => setShowSell(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Product name"><input required className={inputClass} value={form.productName} onChange={e => setForm({...form,productName:e.target.value})} placeholder="e.g. Urea 45 kg bag / Paddy seed / Drip pipe"/></Field><Field label="Product type"><select className={inputClass} value={form.category} onChange={e => setForm({...form,category:e.target.value as MarketplaceCategory})}><option value="Inputs">Fertilizers / Pesticides / Bio Inputs</option><option value="Seeds">Seeds</option><option value="Equipment">Equipment / Irrigation / Farm Tools</option><option value="Crops">Crops / Farm Produce</option><option value="Vegetables">Vegetables</option><option value="Fruits">Fruits</option></select></Field><Field label="Quantity"><input required type="number" min="0.01" step="0.01" className={inputClass} value={form.quantity} onChange={e => setForm({...form,quantity:e.target.value})}/></Field><Field label="Unit"><select className={inputClass} value={form.unit} onChange={e => setForm({...form,unit:e.target.value})}><option>bag</option><option>kg</option><option>quintal</option><option>tonne</option><option>piece</option><option>litre</option></select></Field><Field label="Price per unit"><input required type="number" min="0" step="0.01" className={inputClass} value={form.price} onChange={e => setForm({...form,price:e.target.value})}/></Field><Field label="Village / district"><input required className={inputClass} value={form.location} onChange={e => setForm({...form,location:e.target.value})} placeholder="Tiruppur, Tamil Nadu"/></Field><div className="sm:col-span-2"><Field label="Description"><textarea rows={3} className={`${inputClass} resize-none`} value={form.description} onChange={e => setForm({...form,description:e.target.value})} placeholder="Brand, grade, pack size, quality, delivery details…"/></Field></div><div className="sm:col-span-2 flex justify-end gap-3"><button type="button" onClick={() => setShowSell(false)} className="rounded-2xl border border-gray-200 px-5 py-3 font-bold text-ink-700">Cancel</button><button type="submit" className="rounded-2xl bg-brand-600 px-5 py-3 font-bold text-white">Publish Product</button></div></form></Modal>}
    {selected && <Modal title={`Order ${selected.productName}`} close={() => setSelected(null)}><form onSubmit={order} className="space-y-4"><div className="rounded-2xl bg-brand-50 p-4 text-sm"><p className="font-bold text-ink-900">{currency(selected.price)} / {selected.unit}</p><p className="mt-1 text-ink-600">{selected.availableQuantity.toLocaleString('en-IN')} {selected.unit} available · {selected.location}</p></div><Field label={`Quantity (${selected.unit})`}><input required type="number" min="0.01" max={selected.availableQuantity} step="0.01" className={inputClass} value={orderQty} onChange={e => setOrderQty(e.target.value)}/></Field><Field label="Note to seller"><textarea rows={3} className={`${inputClass} resize-none`} value={orderNote} onChange={e => setOrderNote(e.target.value)} placeholder="Delivery or product requirements…"/></Field><p className="text-sm font-bold text-ink-900">Estimated total: {currency((Number(orderQty)||0)*selected.price)}</p><button type="submit" className="w-full rounded-2xl bg-brand-600 px-5 py-3 font-bold text-white">Place Order Request</button></form></Modal>}
  </div>;
}
function Notice({text,error=false,close}:{text:string;error?:boolean;close:()=>void}){return <div className={`flex items-center justify-between rounded-2xl border px-4 py-3 text-sm font-semibold ${error?'border-red-100 bg-red-50 text-red-700':'border-brand-100 bg-brand-50 text-brand-800'}`}><span>{text}</span><button onClick={close}><X size={16}/></button></div>}
function Tile({icon:Icon,title,text,onClick}:{icon:typeof Wheat;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className="rounded-2xl border border-gray-100 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-card"><Icon size={22} className="text-brand-600"/><p className="mt-2 font-display font-extrabold text-ink-900">{title}</p><p className="mt-1 text-xs leading-5 text-ink-500">{text}</p></button>}
function CatalogCard({item}:{item:typeof productCatalog[number]}){const Icon=item.category==='Fertilizers'?FlaskConical:item.category==='Pesticides'?Bug:item.category==='Seeds'?Sprout:item.category==='Equipment'?Tractor:item.category==='Irrigation'?Droplets:item.category==='Vegetables'?Sprout:item.category==='Fruits'?Apple:Wheat;return <GlassCard padding="none"><div className="flex h-28 items-center justify-center bg-brand-50 text-brand-700"><Icon size={44} strokeWidth={1.5}/></div><div className="p-5"><span className="rounded-full bg-gray-100 px-2.5 py-1 text-[11px] font-bold text-ink-600">Product Catalog</span><h3 className="mt-3 font-display text-lg font-extrabold text-ink-900">{item.name}</h3><p className="mt-2 text-sm leading-5 text-ink-600">{item.description}</p><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-4"><span className="text-xs font-semibold text-ink-500">Typical unit: {item.unit}</span><span className="rounded-xl bg-brand-50 px-3 py-2 text-xs font-bold text-brand-700">Seller listing required</span></div></div></GlassCard>}
function ProductCard({item,own,buy,remove,currency,dateLabel}:{item:MarketplaceListing;own:boolean;buy:()=>void;remove:()=>void;currency:(n:number)=>string;dateLabel:(s:string)=>string}){const Icon=item.category==='Inputs'?FlaskConical:item.category==='Seeds'?Sprout:item.category==='Equipment'?Wrench:item.category==='Vegetables'?Sprout:item.category==='Fruits'?Apple:Wheat;return <GlassCard padding="none"><div className="flex h-36 items-center justify-center bg-brand-50 text-brand-700"><Icon size={52} strokeWidth={1.5}/></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-brand-50 px-2.5 py-1 text-[11px] font-bold text-brand-700">{label(item)}</span><h3 className="mt-3 font-display text-lg font-extrabold text-ink-900">{item.productName}</h3></div><div className="text-right"><p className="text-lg font-extrabold text-brand-700">{currency(item.price)}</p><p className="text-[11px] text-ink-500">per {item.unit}</p></div></div><p className="mt-2 line-clamp-2 text-sm leading-5 text-ink-600">{item.description}</p><div className="mt-4 space-y-2 text-xs text-ink-500"><div className="flex items-center gap-2"><Package size={14}/>{item.availableQuantity.toLocaleString('en-IN')} {item.unit} available</div><div className="flex items-center gap-2"><MapPin size={14}/>{item.location}</div></div><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-4"><span className="text-xs font-semibold text-ink-500">{item.sellerName} · {dateLabel(item.createdAt)}</span>{own?<button onClick={remove} className="inline-flex items-center gap-1 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700"><Trash2 size={14}/> Remove</button>:<button disabled={item.availableQuantity<=0} onClick={buy} className="rounded-xl bg-brand-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Buy / Order</button>}</div></div></GlassCard>}
function OrderRow({order,userId,update,cancel,dateLabel,currency}:{order:MarketplaceOrder;userId:string;update:(o:MarketplaceOrder,s:'accepted'|'rejected'|'completed')=>void;cancel:(o:MarketplaceOrder)=>void;dateLabel:(s:string)=>string;currency:(n:number)=>string}){const seller=order.sellerId===userId;return <div className="rounded-2xl border border-gray-100 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-ink-900">{order.productName}</p><p className="mt-1 text-xs text-ink-500">{order.quantity} {order.unit} · {currency(order.totalAmount)} · {dateLabel(order.createdAt)}</p></div><span className="w-fit rounded-full bg-gray-100 px-3 py-1 text-xs font-bold capitalize text-ink-700">{order.status}</span></div>{order.buyerNote&&<p className="mt-2 text-sm text-ink-600">Note: {order.buyerNote}</p>}<div className="mt-3 flex flex-wrap gap-2">{seller&&order.status==='pending'&&<><button onClick={()=>update(order,'accepted')} className="inline-flex items-center gap-1 rounded-xl bg-brand-600 px-3 py-2 text-xs font-bold text-white"><Check size={14}/> Accept</button><button onClick={()=>update(order,'rejected')} className="inline-flex items-center gap-1 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700"><Ban size={14}/> Reject</button></>}{seller&&order.status==='accepted'&&<button onClick={()=>update(order,'completed')} className="rounded-xl bg-brand-50 px-3 py-2 text-xs font-bold text-brand-700">Mark completed</button>}{!seller&&order.status==='pending'&&<button onClick={()=>cancel(order)} className="rounded-xl bg-gray-100 px-3 py-2 text-xs font-bold text-ink-700">Cancel order</button>}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-ink-500">{label}</span>{children}</label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><h2 className="font-display text-2xl font-extrabold text-ink-900">{title}</h2><button onClick={close} className="rounded-xl bg-gray-100 p-2" aria-label="Close"><X size={18}/></button></div><div className="mt-6">{children}</div></div></div>}
