create table if not exists public.farm_tasks(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,description text,due_at timestamptz not null,status text not null default 'planned',assignee text,machinery text,created_at timestamptz not null default now());
create table if not exists public.farm_inventory(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,category text,quantity numeric not null default 0,unit text,unit_cost numeric, batch_number text,created_at timestamptz not null default now());
create table if not exists public.irrigation_schedules(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,field_id uuid,scheduled_at timestamptz not null,water_volume_liters numeric,source text,status text default 'planned');
create table if not exists public.farm_equipment(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,equipment_type text,maintenance_due_at timestamptz,fuel_used numeric,service_interval_hours numeric); 
create table if not exists public.farm_sales(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,buyer_name text not null,quantity numeric not null,unit text,unit_price numeric not null,sold_at timestamptz not null,contract_date timestamptz,notes text);
create table if not exists public.soil_tests(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,field_id uuid,tested_at timestamptz not null,nitrogen numeric,phosphorus numeric,potassium numeric,ph numeric,report_url text,notes text);
create table if not exists public.knowledge_articles(id uuid primary key default gen_random_uuid(),title text not null,summary text,source_url text not null,updated_at timestamptz not null default now());
create table if not exists public.community_posts(id uuid primary key default gen_random_uuid(),author_id uuid not null references auth.users(id) on delete cascade,title text not null,body text not null,created_at timestamptz not null default now());
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['farm_tasks','farm_inventory','irrigation_schedules','farm_equipment','farm_sales','soil_tests'] LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('drop policy if exists own_%I on public.%I',t,t); EXECUTE format('create policy own_%I on public.%I for all using (user_id=auth.uid()) with check (user_id=auth.uid())',t,t); END LOOP; END $$;
