const MODEL = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
const FAST_MODEL = process.env.GEMINI_FAST_MODEL || 'gemini-3.5-flash-lite';
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const SYSTEM_INSTRUCTION_BASE = `You are Uzhavan AI, a friendly and knowledgeable agricultural assistant for Indian farmers, specialised in Tamil Nadu farming.
Your expertise covers crop cultivation, Tamil Nadu agri seasons, soil, irrigation, pests and diseases, fertilizers, government schemes, FPOs and weather-based advisories.
Be warm, respectful and practical. Never fabricate live weather, market prices, alerts, expenses, yields, farm records, or crop-health observations. If supplied data is unavailable, say so. For pesticide/fertilizer treatment, encourage label/TNAU/KVK verification.`;
const rateWindowMs=60_000,rateLimit=20,requestLog=new Map();
function json(res,body,status=200){res.status(status);res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(body));}
function getClientIp(req){return String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();}
function allowed(req){const key=getClientIp(req),now=Date.now(),recent=(requestLog.get(key)||[]).filter(t=>now-t<rateWindowMs);if(recent.length>=rateLimit){requestLog.set(key,recent);return false;}recent.push(now);requestLog.set(key,recent);return true;}
function hasBearerToken(req){const a=req.headers.authorization||'';return a.startsWith('Bearer ')&&a.slice(7).trim().length>0;}
function buildSystemInstruction(context,language){let i=SYSTEM_INSTRUCTION_BASE;if(context?.trim())i+=`\n\nFARMER CONTEXT:\n${String(context).trim()}`;if(language&&language!=='en')i+=`\n\nRespond primarily in ${String(language)}.`;return i;}
function normalizeHistory(history){if(!Array.isArray(history))return [];return history.slice(-30).flatMap(item=>item&&(item.role==='user'||item.role==='model')&&item.text?[{role:item.role,parts:[{text:String(item.text).slice(0,12000)}]}]:[]);}
function extractGeminiText(data){const parts=data?.candidates?.[0]?.content?.parts||[];return parts.filter(p=>typeof p?.text==='string').map(p=>p.text).join('').trim();}
async function callGemini(contents,systemInstruction,fastMode=false){const model=fastMode?FAST_MODEL:MODEL;if(!GEMINI_API_KEY)throw new Error('GEMINI_API_KEY is missing on the server.');const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),fastMode?9000:22000);try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:systemInstruction}]},contents,generationConfig:{temperature:0.2,maxOutputTokens:fastMode?768:2048}}),signal:controller.signal});const data=await response.json();if(!response.ok){const e=new Error(data?.error?.message||`Gemini request failed with status ${response.status}`);e.status=response.status;throw e;}const text=extractGeminiText(data);if(!text)throw new Error('Gemini returned an empty response.');return text;}catch(error){if(error?.name==='AbortError')throw new Error('Gemini timed out. Please try again.');throw error;}finally{clearTimeout(timeout);}}
function normalizeError(error){const message=error instanceof Error?error.message:String(error||'Unknown error');console.error('Gemini API error:',message);if(/api key|api_key|invalid.*key|key not valid/i.test(message))return 'The Gemini API key is invalid. Please update GEMINI_API_KEY in Vercel.';if(/quota|resource exhausted|rate limit|429/i.test(message))return 'The Gemini API quota has been reached. Please try again later.';if(/permission|forbidden|403/i.test(message))return 'The Gemini API key does not have permission to use this model.';if(/not found|404|model/i.test(message))return 'The Gemini model is unavailable. Check GEMINI_MODEL or GEMINI_FAST_MODEL in Vercel.';if(/503|unavailable|overloaded/i.test(message))return 'Gemini is temporarily unavailable. Please try again.';if(/timed out/i.test(message))return 'The AI service took too long to respond. Please try again.';return message;}
function getImageData(v){const m=String(v||'').match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m||!m[2]||m[2].length>8_000_000)return null;return{mimeType:m[1],data:m[2]};}
export default async function handler(req,res){if(req.method!=='POST')return json(res,{error:'Method not allowed.'},405);try{if(!hasBearerToken(req))return json(res,{error:'Authentication required.'},401);if(!GEMINI_API_KEY)return json(res,{error:'Gemini API key is not configured on the server.'},503);if(!allowed(req))return json(res,{error:'Too many AI requests. Please wait a minute and try again.'},429);const body=req.body||{},prompt=String(body.prompt||'').trim();if(!prompt)return json(res,{error:'A prompt is required.'},400);if(prompt.length>20_000)return json(res,{error:'Prompt is too large.'},413);const instruction=buildSystemInstruction(body.farmerMemoryContext,body.preferredLanguage);if(body.mode==='image'){const image=getImageData(body.imageDataUri);if(!image)return json(res,{error:'Invalid or oversized image.'},400);const text=await callGemini([{role:'user',parts:[{text:prompt},{inlineData:{mimeType:image.mimeType,data:image.data}}]}],instruction,false);return json(res,{text});}const text=await callGemini([...normalizeHistory(body.history),{role:'user',parts:[{text:prompt}]}],instruction,Boolean(body.fastMode));return json(res,{text},200);}catch(error){console.error('Gemini handler error:',error);const status=Number.isInteger(error?.status)&&error.status>=400&&error.status<600?error.status:500;return json(res,{error:normalizeError(error)},status);}}
